import { title } from "process";

export const medicalSpecialties = [

  "General Physician",
  "Cardiologist",
  "Dermatologist",
  "Pediatrician",
  "Gynecologist",
  "Orthopedic Surgeon",
  "Psychiatrist",
  "ENT Specialist",
  "Neurologist",
  "Ophthalmologist",
  "Dentist",
  "Oncologist",
  "Urologist",
  "Gastroenterologist",
  "Nephrologist",



  "Registered Nurse (RN)",
  "Nurse Practitioner (NP)",
  "Critical Care Nurse (ICU Nurse)",
  "Pediatric Nurse",
  "Emergency Room Nurse (ER Nurse)",
  "Surgical Nurse",
  "Labor and Delivery Nurse",
  "Neonatal Nurse (NICU Nurse)",
  "Home Health Nurse",
  "Community Health Nurse",
  "Psychiatric Nurse",
  "Oncology Nurse",
  "Geriatric Nurse",
  "Travel Nurse",
  "Public Health Nurse",
  "Occupational Health Nurse",
  "School Nurse"
];



export const HYDERABAD_LOCATIONS = [
  "Banjara Hills", "Jubilee Hills", "Gachibowli", "Hitech City", "Madhapur", "Manikonda",
  "Begumpet", "Ameerpet", "Kukatpally", "Secunderabad", "Kondapur", "Miyapur",
  "Mehdipatnam", "Somajiguda", "Dilsukhnagar", "LB Nagar", "Tolichowki", "Kompally",
  "Uppal", "Nallagandla", "Attapur", "Khairatabad", "Panjagutta", "Yousufguda",
  "Erragadda", "SR Nagar", "Moosapet", "RTC X Roads", "Basheerbagh", "Koti",
  "Abids", "Himayatnagar", "Chikkadpally", "Musheerabad", "Amberpet", "Nagole",
  "Charminar", "Malakpet", "Bahadurpura", "Shamshabad", "Rajendra Nagar", "Alwal",
  "ECIL", "Malkajgiri", "Nacharam", "Peerzadiguda", "Hayathnagar",
  "Gandipet", "Patancheru", "Isnapur", "Tellapur", "Tarnaka", "Habsiguda", "Moosarambagh",
  "Sainikpuri", "Bowenpally", "Nizampet", "Bachupally", "Chandanagar", "Beeramguda"
];


// export const All_Medical_Colleges_Names=[
//   "Andaman & Nicobar Islands Institute of Medical Sciences, Port Blair (Andaman Nicobar Islands)",
//   "Alluri Sitharam District Government Medical College, Paderu (Andhra Pradesh)",
//   "Government Medical College, Machilipatnam (Andhra Pradesh)",
//   "ACSR Government Medical College, Nellore (Andhra Pradesh)",
//   "All India Institute of Medical Sciences, Mangalagiri, Vijayawada (Andhra Pradesh)",
//   "Alluri Sitaram Raju Academy of Medical Sciences, Eluru (Andhra Pradesh)",
//   "Andhra Medical College, Visakhapatnam (Andhra Pradesh)",
//   "Apollo Institute of Medical Sciences and Research, Chittoor (Andhra Pradesh)",
//   "Dr. P.S.I. Medical College, Chinoutpalli (Andhra Pradesh)",
//   "Fathima Instt. of Medical Sciences, Kadapa (Andhra Pradesh)",
//   "Gayathri Vidya Parishad Institute of Health Care & Medical Technology, Visakhapatnam (Andhra Pradesh)",
//   "Gandhi Institute of Technology and Management (GITAM University) Deemed, Visakhapatnam (Andhra Pradesh)",
//   "Government Medical College, Ananthapuram (Andhra Pradesh)",
//   "Government Medical College, Eluru (Andhra Pradesh)",
//   "Government Medical College, Nandyal (Andhra Pradesh)",
//   "Government Medical College, Rajamahendravaram (Andhra Pradesh)",
//   "Government medical college, vizianagaram (Andhra Pradesh)",
//   "Government Siddhartha Medical College, Vijaywada (Andhra Pradesh)",
//   "Great Eastern Medical School and Hospital, Srikakulam (Andhra Pradesh)",
//   "GSL Medical College, Rajahmundry (Andhra Pradesh)",
//   "Guntur Medical College, Guntur (Andhra Pradesh)",
//   "Katuri Medical College, Guntur (Andhra Pradesh)",
//   "Konaseema Institute of Medical Sciences & Research Foundation, Amalapuram (Andhra Pradesh)",
//   "Kurnool Medical College, Kurnool (Andhra Pradesh)",
//   "Maharajah Institute of Medical Sciences, Vizianagaram (Andhra Pradesh)",
//   "Narayana Medical College, Nellore (Andhra Pradesh)",
//   "Nimra Institute of Medical Sciences, Krishna Dist. (Andhra Pradesh)",
//   "NRI Institute of Medical Sciences, Visakhapatnam (Andhra Pradesh)",
//   "NRI Medical College, Guntur (Andhra Pradesh)",
//   "PES Institute Of Medical Sciences and Research, Kuppam (Andhra Pradesh)",
//   "Rajiv Gandhi Institute of Medical Sciences, Kadapa (Andhra Pradesh)",
//   "Rajiv Gandhi Institute of Medical Sciences, Ongole (Andhra Pradesh)",
//   "Rajiv Gandhi Institute of Medical Sciences, Srikakulam (Andhra Pradesh)",
//   "Rangaraya Medical College, Kakinada (Andhra Pradesh)",
//   "SV Medical College, Tirupati (Andhra Pradesh)",
//   "Santhiram Medical College, Nandyal (Andhra Pradesh)",
//   "Sri Balaji Medical College, Hospital and Research Instiutute, Chittoor (Andhra Pradesh)",
//   "SVIMS-Sri Padmavathi Medical College for Women, Alipiri Road, Tirupati (Andhra Pradesh)",
//   "Viswabharathi Medical College (Andhra Pradesh)",
//   "Tomo Riba Institute of Health & Medical Sciences, Naharlagun (Arunachal Pradesh)",
//   "Tinsukia Medical College - Assam Pin-786146 (Assam)",
//   "Nalbari Medical College, Nalbari (Assam)",
//   "Gauhati Medical College, Guwahati (Assam)",
//   "All India Institute of Medical Sciences (AIIMS), Guwahati (Assam)",
//   "Silchar Medical College, Silchar (Assam)",
//   "Jorhat Medical College & Hospital, Jorhat (Assam)",
//   "Assam Medial College, Dibrugarh (Assam)",
//   "Lakhimpur Medical College (Assam)",
//   "Diphu Medical College & Hospital, Diphu, Assam (Assam)",
//   "Tezpur Medical College & Hospital, Tezpur (Assam)",
//   "Nagaon Medical College (Assam)",
//   "Kokrajhar Medical College (Assam)",
//   "Dhubri Medical College, Dhubri (Assam)",
//   "Fakhruddin Ali Ahmed Medical College, Barpeta, Assam (Assam)",
//   "Himalaya Medical College and Hospital, Patna, Bihar (Bihar)",
//   "Government Medical College, Purnea (Bihar)",
//   "Mata Gujri Memorial Medical College, Kishanganj (Bihar)",
//   "Patna Medical College, Patna (Bihar)",
//   "Darbhanga Medical College, Lehriasarai (Bihar)",
//   "Katihar Medical College, Katihar (Bihar)",
//   "All India Institute of Medical Sciences, Patna (Bihar)",
//   "Nalanda Medical College, Patna (Bihar)",
//   "Shri Krishna Medical College, Muzzafarpur (Bihar)",
//   "Jawaharlal Nehru Medical College, Bhagalpur (Bihar)",
//   "Anugrah Narayan Magadh Medical College, Gaya (Bihar)",
//   "Radha Devi Jageshwari Memorial Medical College land Hospital (Bihar)",
//   "Shree Narayan Medical Institute and Hospital (Bihar)",
//   "Employees State Insurance Corporation Medical College, Patna (Bihar)",
//   "Jannayak Karpoori Thakur Medical College & Hospital, Madhepura, Bihar (Bihar)",
//   "Netaji Subhas Medical College & Hospital, Amhara, Bihta, Patna (Bihar)",
//   "Lord Buddha Koshi Medical College and Hospital, Saharsa (Bihar)",
//   "Madhubani Medical College, Madhubani (Bihar)",
//   "Government Medical College, Bettiah (Bihar)",
//   "Vardhman Institute of Medical Sciences, Pawapuri, Nalanda (Bihar)",
//   "Indira Gandhi Institute of Medical Sciences, Sheikhpura, Patna (Bihar)",
//   "Narayan Medical College & Hospital, Sasaram (Bihar)",
//   "Government Medical College, Chandigarh (Chandigarh)",
//   "Abhishek Mishra Memorial Medical College & RC Bhiali Distt. Durg CG (Chattisgarh)",
//   "Shri Rawatpura Sarkar Institute of Medical Sciences and Research Atal Nagar, Dist- Raipur (C.G.) (Chattisgarh)",
//   "Late Shri Baliram Kashyap Memorial NDMC Govt. Medical College, Jagdalpur (Chattisgarh)",
//   "All India Institute of Medical Sciences, Raipur (Chattisgarh)",
//   "Government Medical College, Kanker (Chattisgarh)",
//   "Pt. J NM Medical College, Raipur (Chattisgarh)",
//   "Chhattisgarh Institute of Medical Sciences, Bilaspur (Chattisgarh)",
//   "Shri Balaji Institute of Medical Science (Chattisgarh)",
//   "Raipur Institute of Medical Sciences (RIMS), Raipur (Chattisgarh)",
//   "Shri Shankaracharya Institute of Medical Sciences, Bhilai (Chattisgarh)",
//   "Government Medical College, Ambikapur (Surguja), Chhattisgarh (Chattisgarh)",
//   "Government Medical College, Mahasamund (Chattisgarh)",
//   "Government Medical College, Korba (Chattisgarh)",
//   "Government Medical College (Bharat Ratna Shri Atal Bihari Vajpyee Memorial Med. Col.), Rajnandgaon (Chattisgarh)",
//   "Chandulal Chandrakar Memorial Medical College, Durg (Chattisgarh)",
//   "Late Shri Lakhi Ram Agrawal Memorial Govt. Medical College, Raigarh (Chattisgarh)",
//   "NAMO Medical Education and Research Institute, Silvassa (Dadra and Nagar Haveli)",
//   "Vardhman Mahavir Medical College & Safdarjung Hospital, Delhi (Delhi)",
//   "Army College of Medical Sciences, New Delhi (Delhi)",
//   "All India Institute of Medical Sciences, New Delhi (Delhi)",
//   "University College of Medical Sciences & GTB Hospital, New Delhi (Delhi)",
//   "Lady Hardinge Medical College, New Delhi (Delhi)",
//   "Maulana Azad Medical College, New Delhi (Delhi)",
//   "Atal Bihari Vajpayee Institute of Medical Sciences and Dr. RML Hospital, New Delhi (Delhi)",
//   "Dr. Baba Saheb Ambedkar Medical College, Rohini, Delhi (Delhi)",
//   "North Delhi Muncipal Corporation Medical College, Delhi (Delhi)",
//   "Hamdard Institute of Medical Sciences & Research, New Delhi (Delhi)",
//   "Goa Medical College, Panaji (Goa)",
//   "Bhagyoday Medical College (Gujarat)",
//   "SAL Institute of Medical Sciences, Ahmedabad (Gujarat)",
//   "SWAMIINARAYAN INSTITUTE OF MEDICAL SCIENCES & RESEARCH (Gujarat)",
//   "All India Institute of Medical Science, Rajkot (Gujarat)",
//   "Surat Municipal Institute of Medical Education & Research, Surat (Gujarat)",
//   "MP Shah Medical College, Jamnagar (Gujarat)",
//   "BJ Medical College, Ahmedabad (Gujarat)",
//   "Pandit Deendayal Upadhyay Medical College, Rajkot (Gujarat)",
//   "SBKS Medical Instt. & Research Centre, Vadodra (Gujarat)",
//   "CU Shah Medical College, Surendra Nagar (Gujarat)",
//   "Government Medical College, Bhavnagar (Gujarat)",
//   "Medical College, Baroda (Gujarat)",
//   "Smt. N.H.L.Municipal Medical College, Ahmedabad (Gujarat)",
//   "Government Medical College, Surat (Gujarat)",
//   "Dr. Kiran C.Patel Medical College and Research Institute (Gujarat)",
//   "Shantabaa Medical College, Amreli (Gujarat)",
//   "Nootan Medical College and Research Centre, Mehsana (Gujarat)",
//   "Dr. N.D. Desai Faculty of Medical Science and Research, Nadiad (Gujarat)",
//   "Kiran Medical College (Gujarat)",
//   "Zydus Medical College & Hospital, Dahod (Gujarat)",
//   "Banas Medical College and Research Institute, Palanpur, Gujarat (Gujarat)",
//   "GMERS Medical College, Vadnagar, Mehsana (Gujarat)",
//   "Dr. M.K. Shah Medical College & Research Centre, Ahmedabad (Gujarat)",
//   "Parul Institute of Medical Sciences & Research, Vadodara (Gujarat)",
//   "GMERS Medical College, Hadiyol, Himmatnagar (Gujarat)",
//   "GMERS Medical College, Junagadh (Gujarat)",
//   "GMERS Medical College, Valsad (Gujarat)",
//   "GMERS Medical College, Dharpur Patan (Gujarat)",
//   "GMERS Medical College, Gandhinagar (Gujarat)",
//   "GCS Medical College, Ahmedabad (Gujarat)",
//   "GMERS Medical College, Gotri, Vadodara (Gujarat)",
//   "GMERS Medical College, Sola, Ahmedabad (Gujarat)",
//   "Gujarat Adani Institute of Medical Sciences, Bhuj (Gujarat)",
//   "Ahmedabad Municipal Coporation Medical Education Trust Medical College, Ahmedabad (Gujarat)",
//   "Government Medical College, Morbi (Gujarat)",
//   "Government Medical College, Navsari (Gujarat)",
//   "Ananya College of Medicine & Research, Kalol (Gujarat)",
//   "Government Medical College, Panchmahal Godhra (Gujarat)",
//   "Government Medical College, Porbandar (Gujarat)",
//   "GMERS Medical College, Rajpipla (Gujarat)",
//   "Pramukhswami Medical College, Karmsad (Gujarat)",
//   "Maharishi Markandeshwar College of Medical Sciences & Research, Sadopur (Haryana)",
//   "Amrita School of Medicine, Faridabad (Haryana)",
//   "Maharaja Agrasen Medical College, Agroha (Haryana)",
//   "Faculty of Medicine and Health Sciences, Gurgaon (Haryana)",
//   "Pt. B D Sharma Postgraduate Institute of Medical Sciences, Rohtak (Haryana)",
//   "Maharishi Markandeshwar Institute Of Medical Sciences & Research, Mullana, Ambala (Haryana)",
//   "Al Falah School of Medical Sciences & Research Centre, Faridabad (Haryana)",
//   "Kalpana Chawala Govt. Medical College, Karnal, Haryana (Haryana)",
//   "Adesh Medical College and Hospital, Shahabad, Kurukshetra, Haryana (Haryana)",
//   "N.C. Medical College & Hospital, Panipat (Haryana)",
//   "World College of Medical Sciences & Researc, Jhajjar, Haryana (Haryana)",
//   "Employees State Insurance Corporation Medical College, Faridabad (Haryana)",
//   "Shaheed Hasan Khan Mewati Government Medical College, Nalhar (Haryana)",
//   "Shri Atal Bihari Vajpayee Government Medical College, Faridabad (Haryana)",
//   "BPS Government Medical College for Women, Sonepat (Haryana)",
//   "Indira Gandhi Medical College, Shimla (Himachal Pradesh)",
//   "All india Institute of Medical Sciences, Bilaspur (Himachal Pradesh)",
//   "Dr. Radhakrishnan Government Medical College, Hamirpur, H.P (Himachal Pradesh)",
//   "Pt. Jawahar Lal Nehru Government Medical College, Chamba (Himachal Pradesh)",
//   "Shri Lal Bahadur Shastri Government Medical College, Mandi, HP (Himachal Pradesh)",
//   "Government Medical College, Nahan, Sirmour H.P. (Himachal Pradesh)",
//   "Maharishi Markandeshwar Medical College & Hospital, Solan (Himachal Pradesh)",
//   "Dr. Rajendar Prasad Government Medical College, Tanda, H.P (Himachal Pradesh)",
//   "Government Medical College Udhampur (Jammu & Kashmir)",
//   "Government Medical College Handwara (Jammu & Kashmir)",
//   "All India Institute of Medical Science, Vijaypur (Jammu & Kashmir)",
//   "Government Medical College, Jammu (Jammu & Kashmir)",
//   "Government Medical College, Srinagar (Jammu & Kashmir)",
//   "Sher-I-Kashmir Instt. Of Medical Sciences, Srinagar (Jammu & Kashmir)",
//   "Govt. Medical College, Doda. Kashmir (Jammu & Kashmir)",
//   "Government Medical College, Rajouri, J&K (Jammu & Kashmir)",
//   "Government Medical College, Kathua (Jammu & Kashmir)",
//   "Government Medical College, Baramulla (Jammu & Kashmir)",
//   "Government Medical College Anantnag (Jammu & Kashmir)",
//   "Acharya Shri Chander College of Medical Sciences, Jammu (Jammu & Kashmir)",
//   "MG M Medical College, Jamshedpur (Jharkhand)",
//   "All India Institute of Medical Sciences, Deoghar (Jharkhand)",
//   "Shaheed Nirmal Mahto Medical College & Hospital, Dhanbad (Jharkhand)",
//   "Mahadev Lal Goverment Medical College, Madhubani (Bihar)",
//   "BGS Global Institute of Medical Sciences, Bangalore (Karnataka)",
//   "Subbaiah Institute of Medical Sciences, Shimoga, Karnataka (Karnataka)",
//   "Employees State Insurance Corporation Medical College, Bangalore (Karnataka)",
//   "Srinivas Institute of Medical Research Centre, Srinivasnagar, Mangalore (Karnataka)",
//   "Sree Gokulam Medical College Trust & Research Foundation, Trivandrum (Kerala)",
//   "Travancore Medical College, Kollam (Kerala)",
//   "Sree Narayana Instt. of Medical Sciences, Chalakka, Ernakulam (Kerala)",
//   "Government Medical College, Kozhikode, Calicut (Kerala)",
//   "Malankara Orthodox Syrian Church Medical College, Kolenchery (Kerala)",
//   "Government Medical College, Konni (Kerala)",
//   "Government Medical College, Idukki (Kerala)",
//   "Pushpagiri Institute Of Medical Sciences and Research Centre, Tiruvalla (Kerala)",
//   "Government Medical College, Chhindwara, MP (Madhya Pradesh)",
//   "Government Medical College, Shahdol, MP (Madhya Pradesh)",
//   "Government Medical College, Shivpuri, MP (Madhya Pradesh)",
//   "Government Medical College, Ratlam (Madhya Pradesh)",
//   "Government Medical college and District Hospital, Ratnagiri (Maharashtra)",
//   "Mahatma Gandhi Mission Medical College, Vashi (Maharashtra)",
//   "Government Medical College, Parbhani (Maharashtra)",
//   "Parbhani Medical College (Maharashtra)",
//   "Indira Gandhi Medical College & Hospital, Nagpur (Maharashtra)",
//   "Rajiv Gandhi Medical College and Chhatrapati Shivaji Maharaj Hospital, Thane (Maharashtra)",
//   "Dr Vaishampayan Memorial Medical College, Solapur (Maharashtra)",
//   "ACPM Medical College, Dhule (Maharashtra)",
//   "Dr. Vasantrao Pawar Med. Col. Hosp. & Research Centre, Nasik (Maharashtra)",
//   "Bharatratna Atal Bihari Vajpayee Medical College, Pune (Maharashtra)",
//   "Government Medical College, Sindhudurg (Maharashtra)",
//   "Dr. N Y Tasgaonkar Institute of Medical Science Karjat (Maharashtra)",
//   "Mahatma Gandhi Missions Medical College, Navi Mumbai (Maharashtra)",
//   "Government Medical College, Osmanabad (Maharashtra)",
//   "Dr. Rajendra Gode Medical College, Amravati (Maharashtra)",
//   "Bharati Vidyapeeth University Medical College, Pune (Maharashtra)",
//   "Saheed Laxman Nayak Medical College & Hospital, Koraput (Orissa)",
//   "Hi-Tech Medical College & Hospital, Rourkela (Orissa)",
//   "Instt. Of Medical Sciences & SUM Hospital, Bhubaneswar (Orissa)",
//   "Government Medical College, Sundargarh (Orissa)",
//   "All India Institute of Medical Sciences, Bhatinda (Punjab)",
//   "Government Medical College, Patiala (Punjab)",
//   "Government Medical College, Amritsar (Punjab)",
//   "Adesh Institute of Medical Sciences & Research, Bhatinda (Punjab)",
//   "Dr B R Ambedkar State Institute of Medical Sciences, SAS Nagar , Mohali (Punjab)",
//   "Chintpurni Medical College, Pathankot, Gurdaspur (Punjab)",
//   "Punjab Institute of Medical Sciences, Jalandhar (Punjab)",
//   "Government Medical College, Jhunjhunu (Rajasthan)",
//   "Sudha Medical College, Kota, Rajasthan (Rajasthan)",
//   "Vyas Medical College & Hospital Jodhpur, Rajasthan (Rajasthan)",
//   "Government Medical College, Baran (Rajasthan)",
//   "Government Medical College, Nagaur (Rajasthan)",
//   "Government Medical College, Banswara (Rajasthan)",
//   "JIET Medical College and Hospital Jodhpur (Rajasthan)",
//   "K A P Viswanathan Government Medical College, Trichy (Tamil Nadu)",
//   "Sri Ramachandra Medical College & Research Institute, Chennai (Tamil Nadu)",
//   "KanyaKumari Government Medical College, Asaripallam (Tamil Nadu)",
//   "Faculty of Medicine , Sri Lalithambigai Medical College and Hospital Chennai (Tamil Nadu)",
//   "VELS Medical College & Hospital Tiruvallur (Tamil Nadu)",
//   "Government Medical College, Dindigul (Tamil Nadu)",
//   "Annapoorna Medical College & Hospital, Salem (Tamil Nadu)",
//   "Dhanalakshmi Srinivasan Medical College and Hospital, Perambalur (Tamil Nadu)",
//   "Government Villupuram Medical College, Villupuram (Tamil Nadu)",
//   "Thiruvarur Govt. Medical College, Thiruvarur (Tamil Nadu)",
//   "Government Medical College, Karimnagar (Telangana)",
//   "GOVERNMENT MEDICAL COLLEGE VIKARABAD (Telangana)",
//   "GOVERNMENT MEDICAL COLLEGE KHAMMAM (Telangana)",
//   "NEELIMA INSTITUTE OF MEDICAL SCIENCES (Telangana)",
//   "Surabhi Institute of Medical Sciences, Siddipet, Telangana (Telangana)"
// ]



// export const All_Medical_Colleges_Names = [

//   "Osmania Medical College, Hyderabad",
//   "Gandhi Medical College, Secunderabad",
//   "Kakatiya Medical College, Warangal",
//   "Government Medical College, Nizamabad",
//   "Government Medical College, Mahabubnagar",
//   "Government Medical College, Siddipet",
//   "Government Medical College, Suryapet",
//   "Government Medical College, Nalgonda",
//   "Government Medical College, Adilabad",
//   "Apollo Institute of Medical Sciences, Hyderabad",
//   "Bhaskar Medical College, Hyderabad",
//   "Chalmeda Anand Rao Institute of Medical Sciences, Karimnagar",
//   "Kamineni Institute of Medical Sciences, Narketpally",
//   "Mamata Medical College, Khammam",
//   "Mediciti Institute of Medical Sciences, Ghanpur",
//   "Malla Reddy Medical College for Women, Hyderabad",
//   "Malla Reddy Institute of Medical Sciences, Hyderabad",
//   "Mahavir Institute of Medical Sciences, Vikarabad",
//   "Dr. Patnam Mahender Reddy Institute of Medical Sciences, Chevella",
//   "Surabhi Institute of Medical Sciences, Siddipet",


//   "Andhra Medical College, Visakhapatnam",
//   "Guntur Medical College, Guntur",
//   "Siddhartha Medical College, Vijayawada",
//   "Kurnool Medical College, Kurnool",
//   "Sri Venkateswara Medical College, Tirupati",
//   "Rangaraya Medical College, Kakinada",
//   "Government Medical College, Anantapur",
//   "Government Medical College, Kadapa",
//   "Government Medical College, Ongole",
//   "Government Medical College, Machilipatnam",
//   "Government Medical College, Vizianagaram",
//   "Government Medical College, Rajahmundry",
//   "Government Medical College, Eluru",
//   "Government Medical College, Nandyal",
//   "Government Medical College, Paderu",
//   "Government Medical College, Srikakulam",
//   "A. C. Subba Reddy Government Medical College, Nellore",
//   "All India Institute of Medical Sciences (AIIMS), Mangalagiri",
//   "Narayana Medical College, Nellore",
//   "Alluri Sitarama Raju Academy of Medical Sciences, Eluru",
//   "Fathima Institute of Medical Sciences, Kadapa",
//   "Katuri Medical College, Guntur",
//   "GSL Medical College, Rajahmundry",
//   "Konaseema Institute of Medical Sciences, Amalapuram",
//   "NRI Medical College, Mangalagiri",
//   "Apollo Institute of Medical Sciences, Chittoor",
//   "Dr. Pinnamaneni Siddhartha Institute of Medical Sciences, Vijayawada",
//   "Sri Balaji Medical College, Tirupati"
// ];


// export const All_Medical_Colleges_Names = [
//   // Telangana Colleges
//   "Osmania Medical College, Telangana, MBBS, MD/MS, BSc Nursing, Allied Health Sciences",
//   "Gandhi Medical College, Telangana, MBBS, MD/MS, BDS, BSc Nursing, Allied Health Sciences",
//   "Kakatiya Medical College, Telangana, MBBS, MD/MS, BSc Nursing, Allied Health Sciences",
//   "ESIC Medical College, Telangana, MBBS, MD/MS, BPT, Allied Health Sciences",
//   "Government Medical College, Nizamabad, Telangana, MBBS, MD/MS, BSc Nursing",
//   "Government Medical College, Mahabubnagar, Telangana, MBBS, MD/MS, BSc Nursing",
//   "Government Medical College, Siddipet, Telangana, MBBS, MD/MS, BSc Nursing",
//   "Government Medical College, Suryapet, Telangana, MBBS, MD/MS, BSc Nursing",
//   "Government Medical College, Nalgonda, Telangana, MBBS, MD/MS, BSc Nursing",
//   "Rajiv Gandhi Institute of Medical Sciences, Telangana, MBBS, MD/MS, BPT",
//   "Apollo Institute of Medical Sciences, Telangana, MBBS, MD/MS, BPT, Nursing, Allied Health Sciences",
//   "Bhaskar Medical College, Telangana, MBBS, MD/MS, Nursing, Allied Health Sciences",
//   "Chalmeda Anand Rao Institute of Medical Sciences, Telangana, MBBS, MD/MS, BSc Nursing",
//   "Kamineni Institute of Medical Sciences, Telangana, MBBS, MD/MS, BSc Nursing",
//   "Deccan College of Medical Sciences, Telangana, MBBS, BDS, BPT, Pharmacy, BSc Nursing",
//   "Malla Reddy Medical College for Women, Telangana, MBBS, MD/MS, BSc Nursing",
//   "Mahavir Institute of Medical Sciences, Telangana, MBBS, MD/MS, BSc Nursing",
//   "Dr. Patnam Mahender Reddy Institute of Medical Sciences, Telangana, MBBS, MD/MS, BSc Nursing",
//   "Surabhi Institute of Medical Sciences, Telangana, MBBS, MD/MS, BSc Nursing",
//   "CMR Institute of Medical Sciences, Telangana, BSc MLT, Allied Health Sciences",
//   "Nova Institute of Medical Sciences, Telangana, MBBS, MD/MS, BSc Nursing",
//   "Prathima Institute of Medical Sciences, Telangana, MBBS, MD/MS, BSc Nursing",
//   "RVM Institute of Medical Sciences, Telangana, MBBS, MD/MS, BSc Nursing",
//   "Shadan Institute of Medical Sciences, Telangana, MBBS, MD/MS, BSc Nursing",
//   "SVS Medical College, Telangana, MBBS, MD/MS, BSc Nursing",
//   "TRR Institute of Medical Sciences, Telangana, MBBS, MD/MS, BSc Nursing",

//   // Andhra Pradesh Colleges
//   "Andhra Medical College, Andhra Pradesh, MBBS, MD/MS, BSc Nursing, Pharmacy",
//   "Guntur Medical College, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
//   "Kurnool Medical College, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
//   "Siddhartha Medical College, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
//   "Sri Venkateswara Medical College, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
//   "Rangaraya Medical College, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
//   "Government Medical College, Eluru, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
//   "Government Medical College, Vizianagaram, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
//   "Government Medical College, Machilipatnam, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
//   "Government Medical College, Nandyal, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
//   "Government Medical College, Rajahmundry, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
//   "Government Medical College, Anantapur, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
//   "Government Medical College, Kadapa, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
//   "All India Institute of Medical Sciences (AIIMS), Mangalagiri, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
//   "DCMS College of Physiotherapy, Andhra Pradesh, BPT, MPT",
//   "Vijaya Institute of Medical Sciences, Andhra Pradesh, BPT, MPT",
//   "PES Institute of Medical Sciences & Research, Andhra Pradesh, MBBS, MD/MS, BPT, BSc Nursing",
//   "Narayana Medical College, Andhra Pradesh, MBBS, MD/MS, BSc Nursing, Allied Health Sciences",
//   "GSL Medical College, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
//   "Katuri Medical College, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
//   "Konaseema Institute of Medical Sciences, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
//   "NRI Medical College, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
//   "Dr. Pinnamaneni Siddhartha Institute of Medical Sciences, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
//   "Sri Balaji Medical College, Andhra Pradesh, MBBS, MD/MS, BSc Nursing"
// ];
export const Main_Filters = ["Client Enquiry", "Placements", "Timesheet", "Referral Pay", "Payments"];

export const ClientEnquiry_Filters = ["Processing", "Converted", "Waiting List", "Lost", ];

export const Placements_Filters = ["On Service", "Replacements", "Termination"];

export const Timesheet_Filters = ["Provider Staff", "Co-provider", "Curate"];

export const ReferralPay_Filters = ["Lead Referral", "Institute Referral", "Staff Referral"];

export const Payments_Filters = ["Invoice Pending", "Collections", "Expenses"];

export const filterColors: Record<string, string> = {

  "Client Enquiry": "bg-blue-200 hover:bg-blue-400 text-gray-800",
  "Placements": "bg-pink-200 hover:bg-pink-400 text-gray-800",
  "Timesheet": "bg-indigo-200 hover:bg-indigo-400 text-gray-800",
  "Referral Pay": "bg-teal-200 hover:bg-teal-400 text-gray-800",
  "Payments": "bg-orange-200 hover:bg-orange-400 text-gray-800",

  "Placced": " text-emerald-600",
  "Processing": "bg-yellow-200 hover:bg-yellow-400 text-gray-800",
  "Waiting List": "bg-purple-200 hover:bg-purple-400 text-gray-800",
  "Converted": "bg-green-200 hover:bg-green-400 text-gray-800",
  "Lost": "bg-red-200 hover:bg-red-400 text-gray-800",


  "On Service": "bg-sky-200 hover:bg-sky-400 text-gray-800",
  "Replacements": "bg-pink-200 hover:bg-pink-400 text-gray-800",
  "Termination": "bg-rose-200 hover:bg-rose-400 text-gray-800",


  "Provider Staff": "bg-indigo-200 hover:bg-indigo-400 text-gray-800",
  "Co-provider": "bg-cyan-200 hover:bg-cyan-400 text-gray-800",
  "Curate": "bg-violet-200 hover:bg-violet-400 text-gray-800",

  "Lead Referral": "bg-emerald-200 hover:bg-emerald-400 text-gray-800",
  "Institute Referral": "bg-lime-200 hover:bg-lime-400 text-gray-800",
  "Staff Referral": "bg-green-200 hover:bg-green-400 text-gray-800",


  "Invoice Pending": "bg-orange-200 hover:bg-orange-400 text-gray-800",
  "Collections": "bg-amber-200 hover:bg-amber-400 text-gray-800",
  "Expenses": "bg-red-200 hover:bg-red-400 text-gray-800",
};



export const PROFESSIONAL_SKILL_OPTIONS: string[] = [
  "Diaper Care",
  "Emergency Care",
  "CPR",
  "Ryle’s Tube Feeding",
  "BiPAP Care",
  "CPAP Care",
  "Oxygen Monitoring",
  "Catheter Care",
  "Stoma Bag Care",
  "Infection Control",
  "Other",
];

export const Home_Assistance_Needs = [
  "Emotional Support",
  "Basic Medical Knowledge",
  "Personal Care",
  "Hygiene",
  "Basic First Aid",
  "Vital Sign Monitoring",
  "Mobility Assistance",
  "Other",
];


export const TestData = [
  {
    AadharCardNo: { iv: "d12f6b8a3c9e4f71", content: "97c3d5b2a1f48e6c3b2e4f9a8d7c1b0e" },
    AnyDeformity: "No",
    BankBranchAddress: "Banjara Hills Rd No 2",
    BankBranchName: "HDFC Bank",
    BranchCity: "Hyderabad",
    BranchPincode: "500034",
    BranchState: "Telangana",
    CertifiedBy: "Red Cross Training",
    CityPostcodeCurrent: "500034",
    CityPostcodePermanent: "500034",
    Complexion: "Wheatish",
    CurrentAddress: "Road No. 2, Banjara Hills, Hyderabad",
    DateOfBirth: "1985-12-05",
    DocumentSkipReason: null,
    Documents: {
      ProfilePic: "https://res.cloudinary.com/demo/image/upload/v1727594215/uploads/profile5.jpg",
      AdharCard: "https://res.cloudinary.com/demo/image/upload/v1727594215/uploads/adhar5.png",
      PanCard: "https://res.cloudinary.com/demo/image/upload/v1727594215/uploads/pan5.png",
      AccountPassBook: "/Icons/PatientDefault.png",
      CertificatOne: "/Icons/PatientDefault.png"
    },
    EmailId: { iv: "c9a4b7321fde5aef", content: "4f7b8a3c6d2e1a9b7c3d5e8f6a4b2c1d" },
    Experience: "8",
    EyeColour: "Brown",
    FirstName: { iv: "e2b3c4d5f6a7b8c9", content: "a3b5c7d9e1f2a4b6c8d0e2f4a6b8c0d" },
    Gender: "Female",
    HCPAdharNumber: "784512345678",
    HCPEmail: "sowmya.hcp@example.com",
    HCPFirstName: "Sowmya",
    HCPSurName: "Sharma",
    HairColour: "Black",
    Height: "5.2",
    HigherEducation: "M.Sc Nursing",
    HigherEducationYearStart: "2010",
    HigherEducationYearEnd: "2012",
    IFSCCode: { iv: "f3c2b1a4d5e6c7b8", content: "1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e" },
    Languages: "Telugu, English, Hindi",
    MaritalStatus: "Married",
    MobileNumber: { iv: "b8f6e4d2c1a3b5c7", content: "7f6e5d4c3b2a1f0e9d8c7b6a5e4d3c2" },
    MoleBodyMark1: "Small mole near chin",
    MoleBodyMark2: null,
    PANNumber: { iv: "a6b5c4d3e2f1a0b9", content: "c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6" },
    PaymentBankAccountNumber: { iv: "c1d2e3f4a5b6c7d8", content: "f6e5d4c3b2a1908f7e6d5c4b3a2f1e0d" },
    PaymentBankName: { iv: "d4c3b2a1f0e9d8c7", content: "b1a2c3d4e5f6a7b8c9d0e1f2a3b4c5d6" },
    PaymentService: "Online",
    PermanentAddress: "Banjara Hills, Hyderabad",
    PreferredService: "Home Visit",
    ProfessionalEducation: "Critical Care Certification",
    ProfessionalEducationYearStart: "2013",
    ProfessionalEducationYearEnd: "2014",
    ProfessionalSkill: "Wound Care",
    ProfessionalWork1: "KIMS Hospital",
    ProfessionalWork2: "Care@Home",
    ProfessionalSkills: ["Diaper", "Bathing", "Bedding",],
    ProfilePic: "https://res.cloudinary.com/demo/image/upload/v1727594215/uploads/profile5.jpg",
    RationCardNo: null,
    Reference1Name: "Meena",
    Reference1Relationship: "Friend",
    Reference1Mobile: { iv: "f4e3d2c1b0a9f8e7", content: "2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d" },
    Reference2Name: "Ravi",
    Reference2Relationship: "Brother",
    Reference2Mobile: { iv: "e7f6d5c4b3a2f1e0", content: "9f8e7d6c5b4a3f2e1d0c9b8a7e6d5c4" },
    RegistrationCouncil: "Telangana Nursing Council",
    RegistrationNo: "TNC20151234",
    ReportCurrentHealthProblems: "None",
    ReportPreviousHealthProblems: "Appendectomy 2012",
    ServiceHours12hrs: true,
    ServiceHours24hrs: false,
    Specialties: "Post-op care",
    Surname: { iv: "f0e1d2c3b4a59687", content: "5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d" },
    Title: "Ms.",
    Type: "Nurse",
    UserId: "5f3a2b1c-4d5e-6f70-8123-9a0b1c2d3e4f",
    VoterIDNo: null,
    Weight: "62",
    userType: "HCA"
  },

  {
    AadharCardNo: { iv: "b2a1c3d4e5f67890", content: "d0c9b8a7e6f5d4c3b2a19087654321ef" },
    AnyDeformity: "Yes",
    BankBranchAddress: "Secunderabad Cantonment",
    BankBranchName: "State Bank of India",
    BranchCity: "Secunderabad",
    BranchPincode: "500003",
    BranchState: "Telangana",
    CertifiedBy: "Government Medical College",
    CityPostcodeCurrent: "500003",
    CityPostcodePermanent: "500003",
    Complexion: "Dark",
    CurrentAddress: "Ekbal Singh Rd, Secunderabad",
    DateOfBirth: "1978-08-18",
    DocumentSkipReason: "Missing Certificate",
    Documents: {
      ProfilePic: "/Icons/DefaultProfileIcon.png",
      AdharCard: "https://res.cloudinary.com/demo/image/upload/v1727594215/uploads/adhar6.png"
    },
    EmailId: { iv: "a1b2c3d4e5f6a7b8", content: "e1f2a3b4c5d6e7f8091a2b3c4d5e6f7a" },
    Experience: "18",
    EyeColour: "Black",
    FirstName: { iv: "c3b2a1f4e5d6c7b8", content: "7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d" },
    Gender: "Male",
    HCPAdharNumber: "789012345678",
    HCPEmail: "manoj.hcp@example.net",
    HCPFirstName: "Manoj",
    HCPSurName: "Rao",
    HairColour: "Grey",
    Height: "5.8",
    IFSCCode: { iv: "e5d4c3b2a1f0e9d8", content: "0f1e2d3c4b5a69788796a5b4c3d2e1f0" },
    Languages: "Telugu, Hindi",
    MaritalStatus: "Widowed",
    MobileNumber: { iv: "d3c4b5a6e7f8d9c0", content: "1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d" },
    MoleBodyMark1: "Large scar right forearm",
    MoleBodyMark2: "Mole on left thigh",
    PANNumber: { iv: "f9e8d7c6b5a4f3e2", content: "2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e" },
    PaymentBankAccountNumber: { iv: "c2d3e4f5a6b7c8d9", content: "3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f" },
    PaymentBankName: { iv: "b1c2d3e4f5a6b7c8", content: "4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a" },
    PaymentService: "Offline",
    PermanentAddress: "Secunderabad",
    PreferredService: "Hospital",
    ProfessionalEducation: "GNM",
    ProfessionalEducationYearStart: "1998",
    ProfessionalEducationYearEnd: "2001",
    ProfessionalSkill: "Geriatric Care",
    ProfessionalWork1: "Government Hospital",
    ProfessionalWork2: "Private Clinic",
    ProfessionalSkills: ["Diaper", "Bedding", "Brushing"],
    ProfilePic: "/Icons/DefaultProfileIcon.png",
    RationCardNo: null,
    Reference1Name: "Suresh",
    Reference1Relationship: "Colleague",
    Reference1Mobile: { iv: "e1d2c3b4a5f6e7d8", content: "5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b" },
    Reference2Name: "Lakshmi",
    Reference2Relationship: "Daughter",
    Reference2Mobile: { iv: "f2a3b4c5d6e7f8a9", content: "6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c" },
    RegistrationCouncil: "Telangana Nursing Council",
    RegistrationNo: "TNC19981234",
    ReportCurrentHealthProblems: "Diabetes Type II",
    ReportPreviousHealthProblems: "Hypertension",
    ServiceHours12hrs: false,
    ServiceHours24hrs: true,
    Specialties: "Geriatric & Palliative Care",
    Surname: { iv: "a9b8c7d6e5f4a3b2", content: "7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e" },
    Title: "Mr.",
    Type: "Senior Nurse",
    UserId: "7a6b5c4d-3e2f-1a0b-9c8d-7e6f5a4b3c2d",
    VoterIDNo: null,
    Weight: "78",
    userType: "HCA"
  },

  {
    AadharCardNo: { iv: "e9d8c7b6a5f4e3d2", content: "9d8c7b6a5f4e3d2c1b0a9876543210ff" },
    AnyDeformity: "No",
    BankBranchAddress: "Malkajgiri Main Road",
    BankBranchName: "Union Bank",
    BranchCity: "Malkajgiri",
    BranchPincode: "500047",
    BranchState: "Telangana",
    CertifiedBy: "Private Trainer",
    CityPostcodeCurrent: "500047",
    CityPostcodePermanent: "500047",
    Complexion: "Fair",
    CurrentAddress: "Malkajgiri, Hyderabad",
    DateOfBirth: "1992-06-09",
    DocumentSkipReason: "PAN expired",
    Documents: {
      ProfilePic: "/Icons/DefaultProfileIcon.png",
      AdharCard: "https://res.cloudinary.com/demo/image/upload/v1727594215/uploads/adhar7.png",
      PanCard: "https://res.cloudinary.com/demo/image/upload/v1727594215/uploads/pan7.png"
    },
    EmailId: { iv: "d7c6b5a4e3f2d1c0", content: "0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d" },
    Experience: "6",
    EyeColour: "Hazel",
    FirstName: { iv: "b7a6c5d4e3f2a1b0", content: "1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d" },
    Gender: "Female",
    HCPAdharNumber: "745612349012",
    HCPEmail: "rekha.hcp@mail.com",
    HCPFirstName: "Rekha",
    HCPSurName: "Naidu",
    HairColour: "Black",
    Height: "5.5",
    IFSCCode: { iv: "a2b3c4d5e6f7a8b9", content: "8a7b6c5d4e3f2a1b0c9d8e7f6a5b4c3" },
    Languages: "Telugu, English",
    MaritalStatus: "Single",
    MobileNumber: { iv: "c1b2a3d4e5f6a7b8", content: "9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4" },
    MoleBodyMark1: null,
    MoleBodyMark2: null,
    PANNumber: { iv: "f1e2d3c4b5a6f7e8", content: "abcd1234ef567890abcd1234ef567890" },
    PaymentBankAccountNumber: { iv: "e0f1a2b3c4d5e6f7", content: "1234abcd5678ef901234abcd5678ef90" },
    PaymentBankName: { iv: "d0c1b2a3f4e5d6c7", content: "fedcba9876543210fedcba9876543210" },
    PaymentService: "Online",
    PermanentAddress: "Malkajgiri, Hyderabad",
    PreferredService: "Home Visit",
    ProfessionalEducation: "B.Sc Nursing",
    ProfessionalEducationYearStart: "2011",
    ProfessionalEducationYearEnd: "2014",
    ProfessionalSkill: "Pediatric Care",
    ProfessionalWork1: "Rainbow Hospital",
    ProfessionalWork2: "ChildCare Pvt Ltd",
    ProfessionalSkills: ["Diaper", "Bathing", "Bedding",],
    ProfilePic: "/Icons/DefaultProfileIcon.png",
    RationCardNo: null,
    Reference1Name: "Priya",
    Reference1Relationship: "Friend",
    Reference1Mobile: { iv: "a9b8c7d6e5f4a3b2", content: "0f1e2d3c4b5a69788796a5b4c3d2e1f0" },
    Reference2Name: "Siva",
    Reference2Relationship: "Manager",
    Reference2Mobile: { iv: "b8c7d6e5f4a3b2c1", content: "1f2e3d4c5b6a79888796a5b4c3d2e1f0" },
    RegistrationCouncil: "Indian Nursing Council",
    RegistrationNo: "INC20140678",
    ReportCurrentHealthProblems: "None",
    ReportPreviousHealthProblems: "Fractured arm (2010)",
    ServiceHours12hrs: true,
    ServiceHours24hrs: false,
    Specialties: "Pediatric & Neonatal care",
    Surname: { iv: "c6d5e4f3a2b1c0d9", content: "9e8d7c6b5a4f3e2d1c0b9a8f7e6d5c4" },
    Title: "Ms.",
    Type: "Pediatric Nurse",
    UserId: "2c4b6a8e-0f1d-3c2b-4e5f-6a7b8c9d0e1f",
    VoterIDNo: null,
    Weight: "58",
    userType: "HCA"
  },

  {
    AadharCardNo: { iv: "c5d6e7f8a9b0c1d2", content: "8c7b6a5d4e3f2a1b0c9d8e7f6a5b4c3d" },
    AnyDeformity: "No",
    BankBranchAddress: "Koti",
    BankBranchName: "Canara Bank",
    BranchCity: "Hyderabad",
    BranchPincode: "500095",
    BranchState: "Telangana",
    CertifiedBy: null,
    CityPostcodeCurrent: "500095",
    CityPostcodePermanent: "500095",
    Complexion: "Fair",
    CurrentAddress: "Koti, Afzal Gunj, Hyderabad",
    DateOfBirth: "1990-02-14",
    DocumentSkipReason: "ProfilePic missing",
    Documents: {
      ProfilePic: "/Icons/PatientDefault.png",
      AdharCard: "/Icons/PatientDefault.png"
    },
    EmailId: { iv: "b3a2c1d4e5f6a7b8", content: "f1e2d3c4b5a6f7e8d9c0b1a2f3e4d5c6" },
    Experience: "5",
    EyeColour: "Black",
    FirstName: { iv: "d4e5f6a7b8c9d0e1", content: "0a9b8c7d6e5f4a3b2c1d0e9f8a7b6c5d" },
    Gender: "Female",
    HCPAdharNumber: "745600123456",
    HCPEmail: "neha.hcp@domain.com",
    HCPFirstName: "Neha",
    HCPSurName: "K",
    HairColour: "Black",
    Height: "5.3",
    IFSCCode: { iv: "e4f3d2c1b0a9f8e7", content: "a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6" },
    Languages: "Telugu, English",
    MaritalStatus: "Single",
    MobileNumber: { iv: "a1b2c3d4e5f6a7b8", content: "1234567890abcdef1234567890abcdef" },
    MoleBodyMark1: "Small mole behind right ear",
    MoleBodyMark2: null,
    PANNumber: { iv: "f2e3d4c5b6a7f8e9", content: "abcdef1234567890abcdef1234567890" },
    PaymentBankAccountNumber: { iv: "c3b4a5d6e7f8c9b0", content: "fedcba0987654321fedcba0987654321" },
    PaymentBankName: { iv: "b2a3c4d5e6f7b8c9", content: "11223344556677889900aabbccddeeff" },
    PaymentService: "Online",
    PermanentAddress: "Koti, Hyderabad",
    PreferredService: "Hospital",
    ProfessionalEducation: "GNM",
    ProfessionalEducationYearStart: "2010",
    ProfessionalEducationYearEnd: "2013",
    ProfessionalSkill: "Post-op care",
    ProfessionalWork1: "Yashoda Hospital",
    ProfessionalWork2: "Care Homes",
    ProfessionalSkills: ["Diaper", "Bathing", "Bedding",],
    ProfilePic: "/Icons/PatientDefault.png",
    RationCardNo: null,
    Reference1Name: "Asha",
    Reference1Relationship: "Friend",
    Reference1Mobile: { iv: "d1c2b3a4e5f6d7c8", content: "0f1e2d3c4b5a69788796a5b4c3d2e1f0" },
    Reference2Name: "Vikram",
    Reference2Relationship: "Supervisor",
    Reference2Mobile: { iv: "e2f3a4b5c6d7e8f9", content: "1e2d3c4b5a69788796a5b4c3d2e1f0a" },
    RegistrationCouncil: "Telangana Nursing Council",
    RegistrationNo: "TNC20130654",
    ReportCurrentHealthProblems: "None",
    ReportPreviousHealthProblems: "Thyroid, treated",
    ServiceHours12hrs: true,
    ServiceHours24hrs: false,
    Specialties: "Post-op & Wound care",
    Surname: { iv: "f3e4d5c6b7a8f9e0", content: "9f8e7d6c5b4a3f2e1d0c9b8a7e6d5c4" },
    Title: "Ms.",
    Type: "Nurse",
    UserId: "8b7c6d5e-4f3a-2b1c-0a9d-8e7f6a5b4c3d",
    VoterIDNo: null,
    Weight: "60",
    userType: "HCA"
  },

  {
    AadharCardNo: { iv: "a7b8c9d0e1f2a3b4", content: "fedcba98765432100123456789abcdef" },
    AnyDeformity: "No",
    BankBranchAddress: "Jubilee Hills",
    BankBranchName: "Axis Bank",
    BranchCity: "Hyderabad",
    BranchPincode: "500033",
    BranchState: "Telangana",
    CertifiedBy: "Apollo Nursing School",
    CityPostcodeCurrent: "500033",
    CityPostcodePermanent: "500033",
    Complexion: "Fair",
    CurrentAddress: "Jubilee Hills, Hyderabad",
    DateOfBirth: "1997-09-30",
    DocumentSkipReason: null,
    Documents: {
      ProfilePic: "https://res.cloudinary.com/demo/image/upload/v1727594215/uploads/profile9.jpg",
      AdharCard: "https://res.cloudinary.com/demo/image/upload/v1727594215/uploads/adhar9.png",
      PanCard: "https://res.cloudinary.com/demo/image/upload/v1727594215/uploads/pan9.png"
    },
    EmailId: { iv: "e6f5d4c3b2a19087", content: "0abc1def23456789abcdeffedcba9876" },
    Experience: "2",
    EyeColour: "Brown",
    FirstName: { iv: "b9a8c7d6e5f41321", content: "1234abcd5678ef901234abcd5678ef90" },
    Gender: "Female",
    HCPAdharNumber: "745623456789",
    HCPEmail: "isha.hcp@sample.org",
    HCPFirstName: "Isha",
    HCPSurName: "Patel",
    HairColour: "Black",
    Height: "5.1",
    IFSCCode: { iv: "c9d8e7f6a5b4c3d2", content: "a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6" },
    Languages: "English, Telugu",
    MaritalStatus: "Single",
    MobileNumber: { iv: "b0a1c2d3e4f5a6b7", content: "87654321fedcba0987654321fedcba09" },
    MoleBodyMark1: null,
    MoleBodyMark2: null,
    PANNumber: { iv: "d8c7b6a5f4e3d2c1", content: "98badcfe76543210fedcba9876543210" },
    PaymentBankAccountNumber: { iv: "c0d1e2f3a4b5c6d7", content: "0f9e8d7c6b5a4f3e2d1c0b9a8f7e6d5" },
    PaymentBankName: { iv: "a0b1c2d3e4f5a6b7", content: "1122aabb3344ccdd5566eeff77889900" },
    PaymentService: "Online",
    PermanentAddress: "Jubilee Hills, Hyderabad",
    PreferredService: "Home Visit",
    ProfessionalEducation: "B.Sc Nursing",
    ProfessionalEducationYearStart: "2015",
    ProfessionalEducationYearEnd: "2018",
    ProfessionalSkill: "Basic Life Support",
    ProfessionalWork1: "Sunshine Clinic",
    ProfessionalWork2: "HomeCare Pvt Ltd",
    ProfessionalSkills: ["Diaper", "Bathing", "Bedding",],
    ProfilePic: "https://res.cloudinary.com/demo/image/upload/v1727594215/uploads/profile9.jpg",
    RationCardNo: null,
    Reference1Name: "Anu",
    Reference1Relationship: "Colleague",
    Reference1Mobile: { iv: "f6e5d4c3b2a19087", content: "9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4" },
    Reference2Name: "Ramesh",
    Reference2Relationship: "Father",
    Reference2Mobile: { iv: "e5f4d3c2b1a09876", content: "8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3" },
    RegistrationCouncil: "Indian Nursing Council",
    RegistrationNo: "INC20180123",
    ReportCurrentHealthProblems: "None",
    ReportPreviousHealthProblems: "Asthma (childhood)",
    ServiceHours12hrs: true,
    ServiceHours24hrs: false,
    Specialties: "Home Postnatal Care",
    Surname: { iv: "f8e7d6c5b4a39102", content: "07f6e5d4c3b2a1909f8e7d6c5b4a3910" },
    Title: "Ms.",
    Type: "Nurse",
    UserId: "9c8b7a6d-5e4f-3a2b-1c0d-9e8f7a6b5c4d",
    VoterIDNo: null,
    Weight: "55",
    userType: "HCA"
  },

  {
    AadharCardNo: { iv: "f0e1d2c3b4a59687", content: "abcdef0123456789fedcba9876543210" },
    AnyDeformity: "No",
    BankBranchAddress: "Kothapet",
    BankBranchName: "IDBI Bank",
    BranchCity: "Hyderabad",
    BranchPincode: "500060",
    BranchState: "Telangana",
    CertifiedBy: "Private Nursing School",
    CityPostcodeCurrent: "500060",
    CityPostcodePermanent: "500060",
    Complexion: "Wheatish",
    CurrentAddress: "Kothapet, Hyderabad",
    DateOfBirth: "1982-01-20",
    DocumentSkipReason: null,
    Documents: {
      ProfilePic: "/Icons/DefaultProfileIcon.png",
      AdharCard: "/Icons/DefaultProfileIcon.png"
    },
    EmailId: { iv: "aabbccddeeff0011", content: "00112233445566778899aabbccddeeff" },
    Experience: "12",
    EyeColour: "Black",
    FirstName: { iv: "1122334455667788", content: "8899aabbccddeeff0011223344556677" },
    Gender: "Male",
    HCPAdharNumber: "745699001122",
    HCPEmail: "victor.hcp@sample.com",
    HCPFirstName: "Victor",
    HCPSurName: "D'Souza",
    HairColour: "Salt & Pepper",
    Height: "5.9",
    IFSCCode: { iv: "2233445566778899", content: "7766554433221100ffeeddccbbaa9988" },
    Languages: "English, Telugu, Konkani",
    MaritalStatus: "Married",
    MobileNumber: { iv: "3344556677889900", content: "aabbccddeeff00112233445566778899" },
    MoleBodyMark1: "Birthmark left chest",
    MoleBodyMark2: "Scar above left eyebrow",
    PANNumber: { iv: "4455667788990011", content: "11223344556677889900aabbccddeeff" },
    PaymentBankAccountNumber: { iv: "5566778899001122", content: "22334455667788990011aabbccddeeff" },
    PaymentBankName: { iv: "6677889900112233", content: "33445566778899001122aabbccddeeff" },
    PaymentService: "Offline",
    PermanentAddress: "Kothapet, Hyderabad",
    PreferredService: "Hospital",
    ProfessionalEducation: "B.Sc Nursing",
    ProfessionalEducationYearStart: "2000",
    ProfessionalEducationYearEnd: "2003",
    ProfessionalSkill: "ICU & Emergency",
    ProfessionalWork1: "Apollo General",
    ProfessionalWork2: "Global Hospitals",
    ProfessionalSkills: ["ICU Support", "Ventilator Care", "Emergency Response"],
    ProfilePic: "/Icons/DefaultProfileIcon.png",
    RationCardNo: null,
    Reference1Name: "George",
    Reference1Relationship: "Colleague",
    Reference1Mobile: { iv: "7788990011223344", content: "44556677889900aabbccddeeff112233" },
    Reference2Name: "Latha",
    Reference2Relationship: "Wife",
    Reference2Mobile: { iv: "8899001122334455", content: "55667788990011aabbccddeeff223344" },
    RegistrationCouncil: "Indian Nursing Council",
    RegistrationNo: "INC20031234",
    ReportCurrentHealthProblems: "Hypertension (controlled)",
    ReportPreviousHealthProblems: "None",
    ServiceHours12hrs: false,
    ServiceHours24hrs: true,
    Specialties: "ICU / Emergency",
    Surname: { iv: "9900112233445566", content: "66778899001122334455aabbccddeeff" },
    Title: "Mr.",
    Type: "Senior Nurse",
    UserId: "0a1b2c3d-4e5f-6a7b-8c9d-0e1f2a3b4c5d",
    VoterIDNo: null,
    Weight: "80",
    userType: "HCA"
  },

  {
    AadharCardNo: { iv: "9988776655443322", content: "5566778899aabbccddeeff0011223344" },
    AnyDeformity: "No",
    BankBranchAddress: "Ameerpet",
    BankBranchName: "Punjab National Bank",
    BranchCity: "Hyderabad",
    BranchPincode: "500016",
    BranchState: "Telangana",
    CertifiedBy: "Government Nursing College",
    CityPostcodeCurrent: "500016",
    CityPostcodePermanent: "500016",
    Complexion: "Fair",
    CurrentAddress: "Ameerpet, Hyderabad",
    DateOfBirth: "1994-07-21",
    DocumentSkipReason: null,
    Documents: {
      ProfilePic: "https://res.cloudinary.com/demo/image/upload/v1727594215/uploads/profile11.jpg",
      AdharCard: "https://res.cloudinary.com/demo/image/upload/v1727594215/uploads/adhar11.png"
    },
    EmailId: { iv: "7766554433221100", content: "99aabbccddeeff001122334455667788" },
    Experience: "4",
    EyeColour: "Black",
    FirstName: { iv: "554433221100ffee", content: "ffee00112233445566778899aabbccdd" },
    Gender: "Male",
    HCPAdharNumber: "745655443322",
    HCPEmail: "mehul.hcp@health.org",
    HCPFirstName: "Mehul",
    HCPSurName: "Singh",
    HairColour: "Black",
    Height: "5.7",
    IFSCCode: { iv: "aa1122bb3344cc55", content: "cc33445566778899aa1122bb3344cc55" },
    Languages: "Hindi, English, Telugu",
    MaritalStatus: "Single",
    MobileNumber: { iv: "ccbbaa9988776655", content: "887766554433221100ffeeddccbbaa99" },
    MoleBodyMark1: null,
    MoleBodyMark2: null,
    PANNumber: { iv: "bbccddeeff001122", content: "00112233445566778899aabbccddeeff" },
    PaymentBankAccountNumber: { iv: "ddeeff0011223344", content: "44556677889900aabbccddeeff112233" },
    PaymentBankName: { iv: "eeff001122334455", content: "55667788990011aabbccddeeff223344" },
    PaymentService: "Online",
    PermanentAddress: "Ameerpet, Hyderabad",
    PreferredService: "Home Visit",
    ProfessionalEducation: "B.Sc Nursing",
    ProfessionalEducationYearStart: "2013",
    ProfessionalEducationYearEnd: "2016",
    ProfessionalSkill: "Home Care & Elderly Assistance",
    ProfessionalWork1: "CareNow",
    ProfessionalWork2: "ElderCare Services",
    ProfessionalSkills: ["Diaper", "Bathing", "Bedding",],
    ProfilePic: "https://res.cloudinary.com/demo/image/upload/v1727594215/uploads/profile11.jpg",
    RationCardNo: null,
    Reference1Name: "Nitin",
    Reference1Relationship: "Manager",
    Reference1Mobile: { iv: "1122334455667788", content: "7766554433221100ffeeddccbbaa9988" },
    Reference2Name: "Shweta",
    Reference2Relationship: "Sister",
    Reference2Mobile: { iv: "2233445566778899", content: "887766554433221100ffeeddccbbaa99" },
    RegistrationCouncil: "Telangana Nursing Council",
    RegistrationNo: "TNC20160111",
    ReportCurrentHealthProblems: "None",
    ReportPreviousHealthProblems: "Broken leg (2018)",
    ServiceHours12hrs: true,
    ServiceHours24hrs: false,
    Specialties: "Elder Care, Mobility Support",
    Surname: { iv: "33445566778899aa", content: "aabbccddeeff00112233445566778899" },
    Title: "Mr.",
    Type: "Caregiver",
    UserId: "1f2e3d4c-5b6a-7980-1c2d-3e4f5a6b7c8d",
    VoterIDNo: null,
    Weight: "72",
    userType: "HCA"
  },
  {
    AadharCardNo: { iv: "a34d57a92a671d9f879b54cd9230c8b4", content: "b59c58d37a28f84e6f77b6a90c1fd432" },
    AnyDeformity: "No",
    BankBranchAddress: "Kukatpally",
    BankBranchName: "HDFC Bank",
    BranchCity: "Hyderabad",
    BranchPincode: "500072",
    BranchState: "Telangana",
    CertifiedBy: "Apollo Training Institute",
    CityPostcodeCurrent: "500072",
    CityPostcodePermanent: "500072",
    Complexion: "Fair",
    CurrentAddress: "KPHB Phase 2, Hyderabad",
    DateOfBirth: "1995-04-15",
    DocumentSkipReason: "All documents verified",
    Documents: {
      ProfilePic: "https://res.cloudinary.com/demo/image/upload/v1727594215/uploads/profile1.jpg",
      AdharCard: "/Icons/PatientDefault.png",
      PanCard: "/Icons/PatientDefault.png",
      AccountPassBook: "/Icons/PatientDefault.png",
      CertificatOne: "/Icons/PatientDefault.png"
    },
    EmailId: { iv: "5f63a91bc292a53c", content: "c56a8f1a48bc6b9a82739d9a53e77b62" },
    Experience: "3",
    EyeColour: "Black",
    FirstName: { iv: "de7f214f6d3cb07c", content: "982b7109b781f4f1b83d1b56e8a0c2e1" },
    Gender: "Female",
    HCPAdharNumber: "784512457895",
    HCPEmail: "kiranahcp@gmail.com",
    HCPFirstName: "Kirana",
    HCPSurName: "Reddy",
    HairColour: "Brown",
    Height: "5.3",
    HigherEducation: "B.Sc Nursing",
    HigherEducationYearStart: "2018",
    HigherEducationYearEnd: "2021",
    IFSCCode: { iv: "ca63bfe14829d9f1", content: "7c4d3a9033ba4b7c984cb1c22a7e1ad4" },
    Languages: "Telugu, English",
    MaritalStatus: "Married",
    MobileNumber: { iv: "6b5e91a403db2dca", content: "5fd8a17c94fbd72a99ed84b6ef62e833" },
    MoleBodyMark1: "Small mole near left eye",
    MoleBodyMark2: "Birthmark on right shoulder",
    PANNumber: { iv: "8d73c3413df5bca2", content: "b03a9d38c4a5e78c49f8a941f3d79a66" },
    PaymentBankAccountNumber: { iv: "9c31b52a48c3a76b", content: "b981c5634d8394e8f2e7f85b0fa3c982" },
    PaymentBankName: { iv: "bd43c12a92c6b711", content: "5a1dc47fbd8f84b5cf7b9f55a68a92e2" },
    PaymentService: "Online",
    PermanentAddress: "Kukatpally, Hyderabad",
    PreferredService: "Home Care",
    ProfessionalEducation: "Nursing",
    ProfessionalEducationYearStart: "2018",
    ProfessionalEducationYearEnd: "2021",
    ProfessionalSkill: "Patient Care",
    ProfessionalWork1: "Care Hospitals",
    ProfessionalWork2: "Apollo HomeCare",
    ProfessionalSkills: ["Injection", "Feeding", "Blood Pressure"],
    ProfilePic: "https://res.cloudinary.com/demo/image/upload/v1727594215/uploads/profile1.jpg",
    RationCardNo: null,
    Reference1Name: "Swapna",
    Reference1Relationship: "Colleague",
    Reference1Mobile: { iv: "e53a17f8a6c94b3a", content: "4e82d97a61a2d97a861a96b4c9fae6c2" },
    Reference2Name: "Rajesh",
    Reference2Relationship: "Neighbor",
    Reference2Mobile: { iv: "b76c3b04c28c9a52", content: "d11f9b35a61c7b8f964f2b3a11a6a3cf" },
    RegistrationCouncil: "Indian Nursing Council",
    RegistrationNo: "NUR20210456",
    ReportCurrentHealthProblems: "No issues",
    ReportPreviousHealthProblems: "None",
    ServiceHours12hrs: true,
    ServiceHours24hrs: false,
    Specialties: "Elder Care",
    Surname: { iv: "f931a8f6b98d7c33", content: "3a2c85e6c96b9d77a3b99e1c8d6b7a61" },
    Title: "Mrs.",
    Type: "Certified Nurse",
    UserId: "c9b721d9-71b3-4e72-84cd-2c1e2b772ff5",
    VoterIDNo: null,
    Weight: "58",
    userType: "HCA"
  },

  {
    AadharCardNo: { iv: "7d84c6b1a6f8e29b", content: "ab17d82f9a7e83f991a7d0eaa1cb5728" },
    AnyDeformity: "Yes",
    BankBranchAddress: "Lingampally",
    BankBranchName: "SBI",
    BranchCity: "Hyderabad",
    BranchPincode: "500019",
    BranchState: "Telangana",
    CertifiedBy: "NIMS Hyderabad",
    CityPostcodeCurrent: "500019",
    CityPostcodePermanent: "500019",
    Complexion: "Wheatish",
    CurrentAddress: "Lingampally, Hyderabad",
    DateOfBirth: "1988-03-22",
    DocumentSkipReason: "Missing PAN Card",
    Documents: {
      ProfilePic: "/Icons/DefaultProfileIcon.png",
      AdharCard: "https://res.cloudinary.com/demo/image/upload/v1727594215/uploads/adhar.png"
    },
    EmailId: { iv: "af37bfa1c992e781", content: "8a37a19c8f3e4d9b7a83c1a98c3b2f61" },
    Experience: "10",
    EyeColour: "Black",
    FirstName: { iv: "9b16a1b7e993f9d3", content: "bd71f7a1a48f47b8827a4c2e7a15c6e1" },
    Gender: "Male",
    HCPAdharNumber: "879541258745",
    HCPEmail: "ramkumarhcp@gmail.com",
    HCPFirstName: "Ram",
    HCPSurName: "Kumar",
    HairColour: "Black",
    Height: "5.7",
    IFSCCode: { iv: "a7c3e4f612b2d15f", content: "7b18f4e1c63a8b4f9a83c1f2e61a2a7f" },
    Languages: "Telugu, English, Hindi",
    MaritalStatus: "Married",
    MobileNumber: { iv: "ac1b6a7e1f9a3d8b", content: "9e3a71a6b3d8f41a8b2a6a7f1c4d6e8b" },
    MoleBodyMark1: "Scar on forehead",
    MoleBodyMark2: "Mole on right leg",
    PANNumber: { iv: "bf18a7f6d3a1b2c7", content: "9b17a2e3d4c8f1a6b3d2c4e8a7f1b9e3" },
    PaymentBankAccountNumber: { iv: "a3c9f8b5e7d4a6f1", content: "b6e3d9a1f4b7a8e9c2a1b5d8e3f4c6a9" },
    PaymentBankName: { iv: "c4a1f9b7d8e3a2c1", content: "e3d7b5f8c9a4b1f2d6e3a9c5b8f1a2d4" },
    PaymentService: "Offline",
    PermanentAddress: "Lingampally, Hyderabad",
    PreferredService: "Hospital",
    ProfessionalEducation: "Diploma in Nursing",
    ProfessionalEducationYearStart: "2010",
    ProfessionalEducationYearEnd: "2013",
    ProfessionalSkill: "ICU Support",
    ProfessionalWork1: "NIMS Hyderabad",
    ProfessionalWork2: "Medicover",
    ProfessionalSkills: ["Dressing", "Vitals", "Patient Transfer"],
    ServiceHours12hrs: false,
    ServiceHours24hrs: true,
    Surname: { iv: "f2b4a8e6b1d3a7c9", content: "a9b2f4c1e8d6a3b7f1d2e9a4b3c6a7f8" },
    Weight: "70",
    userType: "HCA"
  },

  {
    AadharCardNo: { iv: "f41c7d3a62b7e91f", content: "b63a8d91e7c41a8f9d7b3a2f1e6c2d5a" },
    AnyDeformity: "No",
    BankBranchAddress: "Madhapur",
    BankBranchName: "ICICI Bank",
    BranchCity: "Hyderabad",
    BranchPincode: "500081",
    BranchState: "Telangana",
    CertifiedBy: "LV Prasad Eye Institute",
    Complexion: "Fair",
    CurrentAddress: "Madhapur, Hyderabad",
    DateOfBirth: "1999-11-19",
    EmailId: { iv: "e62b8a1f94d7a2c5", content: "9f3b2a6e8c1a4b9d7a2e5f3b6c8d1a4f" },
    Experience: "4",
    EyeColour: "Brown",
    FirstName: { iv: "b4f7e1a9c6d3b2f8", content: "e7d3a8b2f1c6a9b4f2e3a7b8c1d9f2a6" },
    Gender: "Female",
    HCPAdharNumber: "745899991245",
    HCPEmail: "anjali.hcp@gmail.com",
    HCPFirstName: "Anjali",
    HCPSurName: "Varma",
    HairColour: "Brown",
    Height: "5.4",
    IFSCCode: { iv: "c8b9f1e3a7d4b2f6", content: "e1b2f3a9d8c7a4e5f6b2a7d9c3f1a8e4" },
    Languages: "Telugu, English",
    MaritalStatus: "Single",
    MobileNumber: { iv: "a3b4c5d6e7f8a9b0", content: "b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6" },
    MoleBodyMark1: "Tattoo on left wrist",
    MoleBodyMark2: "Mole on neck",
    PaymentService: "Online",
    PreferredService: "Home Visit",
    ProfessionalEducation: "B.Sc Nursing",
    ProfessionalWork1: "Yashoda Hospitals",
    ProfessionalSkills: ["Injection", "Vitals", "Medication"],
    ProfilePic: "/Icons/DefaultProfileIcon.png",
    Weight: "60",
    userType: "HCA"
  }

]
export const familyRelations = [
  "Father",
  "Mother",
  "Son",
  "Daughter",
  "Brother",
  "Sister",
  "Husband",
  "Wife",
  "Grandfather (Paternal)",
  "Grandmother (Paternal)",
  "Grandfather (Maternal)",
  "Grandmother (Maternal)",
  "Uncle (Paternal)",
  "Aunt (Paternal)",
  "Uncle (Maternal)",
  "Aunt (Maternal)",
  "Cousin (Male)",
  "Cousin (Female)",
  "Nephew",
  "Niece",
  "Father-in-law",
  "Mother-in-law",
  "Brother-in-law",
  "Sister-in-law",
  "Son-in-law",
  "Daughter-in-law",
  "Stepfather",
  "Stepmother",
  "Stepson",
  "Stepdaughter",
  "Godfather",
  "Godmother",
  "Legal Guardian",
  "Other"
];


export const All_Medical_Colleges_Names = [

  "Osmania Medical College, Telangana, MBBS, MD/MS, BPT, BSc Nursing, Medical Lab Technology, Allied Health Sciences, MPH",
  "Gandhi Medical College, Telangana, MBBS, MD/MS, BDS, BPT, BSc Nursing, Allied Health Sciences",
  "Kakatiya Medical College, Telangana, MBBS, MD/MS, BPT, BSc Nursing, Allied Health Sciences",
  "ESIC Medical College, Telangana, MBBS, MD/MS, BPT, Allied Health Sciences",
  "Government Medical College, Nizamabad, Telangana, MBBS, MD/MS, BSc Nursing",
  "Government Medical College, Mahabubnagar, Telangana, MBBS, MD/MS, BSc Nursing",
  "Government Medical College, Siddipet, Telangana, MBBS, MD/MS, BSc Nursing",
  "Government Medical College, Suryapet, Telangana, MBBS, MD/MS, BSc Nursing",
  "Government Medical College, Nalgonda, Telangana, MBBS, MD/MS, BSc Nursing",
  "Rajiv Gandhi Institute of Medical Sciences, Telangana, MBBS, MD/MS, BPT",
  "Deccan College of Medical Sciences, Telangana, MBBS, BDS, BPT, Pharmacy, BSc Nursing",
  "Kamineni Institute of Dental Sciences, Telangana, BDS, Allied Health Sciences",
  "Dr. B.R.K.R. Govt Ayurvedic College, Telangana, BAMS, MD Ayurveda",
  "Govt Nizamia Tibbi College, Telangana, BUMS, MD Unani",
  "Durgabai Deshmukh College of Physiotherapy, Telangana, BPT",
  "Kakatiya College of Physiotherapy, Telangana, BPT",
  "Susruta Institute of Physical Medicine & Rehabilitation, Telangana, BPT",
  "Apollo College of Physiotherapy, Telangana, BPT",
  "Government College of Nursing, Warangal, Telangana, BSc Nursing",
  "Govt College of Nursing, Secunderabad, Telangana, BSc Nursing, MSc Nursing",
  "Angel College of Nursing, Telangana, BSc Nursing",
  "Apollo College of Nursing, Telangana, BSc Nursing, MSc Nursing",
  "Institute of Preventive Medicine/Public Health Labs, Telangana, BSc Medical Lab Technology",
  "Shadan College of Medical Lab Technology, Telangana, BSc MLT",
  "SRM Institute of Medical Sciences & Technology, Telangana, BSc MLT",
  "PIMTECH College of BSc MLT, Telangana, BSc MLT",
  "Shaarvani Institute of Medical Sciences, Telangana, BSc MLT",
  "Indian Institute of Public Health, Telangana, MPH",
  "Andhra Medical College, Andhra Pradesh, MBBS, MD/MS, BSc Nursing, Pharmacy",
  "Guntur Medical College, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
  "Kurnool Medical College, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
  "Siddhartha Medical College, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
  "Sri Venkateswara Medical College, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
  "Rangaraya Medical College, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
  "Government Medical College, Eluru, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
  "Government Medical College, Vizianagaram, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
  "Government Medical College, Machilipatnam, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
  "Government Medical College, Nandyal, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
  "Government Medical College, Rajahmundry, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
  "Government Medical College, Anantapur, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
  "Government Medical College, Kadapa, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
  "All India Institute of Medical Sciences (AIIMS) Mangalagiri, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
  "Dr NRS Government Ayurvedic College, Andhra Pradesh, BAMS, MD Ayurveda",
  "S.V. Ayurvedic College, Tirupati, Andhra Pradesh, BAMS",
  "Sri Adi Shiva Sadguru Ayurvedic Medical College, Andhra Pradesh, BAMS",
  "ASR Homoeopathic Medical College, Andhra Pradesh, BHMS",
  "Kugler Memorial Physiotherapy Degree College, Guntur, Andhra Pradesh, BPT",
  "Sri P. Ramireddy Memorial College of Physiotherapy, Kadapa, Andhra Pradesh, BPT",
  "Alluri Sitarama Raju Academy of Medical Sciences, Andhra Pradesh, MBBS, MD/MS",
  "PES Institute of Medical Sciences & Research, Andhra Pradesh, MBBS, MD/MS, BPT, BSc Nursing",
  "DCMS College of Physiotherapy, Andhra Pradesh, BPT, MPT",
  "Vijaya Institute of Medical Sciences, Andhra Pradesh, BPT, MPT",
  "Narayana Medical College, Andhra Pradesh, MBBS, MD/MS, BSc Nursing, Allied Health Sciences",
  "GSL Medical College, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
  "Katuri Medical College, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
  "Konaseema Institute of Medical Sciences, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
  "NRI Medical College, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
  "Dr. Pinnamaneni Siddhartha Institute of Medical Sciences, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
  "Sri Balaji Medical College, Andhra Pradesh, MBBS, MD/MS, BSc Nursing"
];

export const Headings = ["Client Card – ID", "Patient Card – ID", "Patient Details", "Home Assistance", "Home Needs", "Doctor Needs", "Health Card",]
export const LeadSources = [
  "Pramela Mam",
  "AIG Sunil",
  "Jagdeep P",
  "Arthi",
  "Sravanthi",
  "Pandu",
  "Swaroop I",
  "Soumya Ranjan",
  "Website",
  "Google",
  "Other"
];
export const REFERRAL_SOURCE_TYPES: string[] = [
  "Institute",
  "Individual",
  "Curate Staff",
  "HCA",
  "HCN",
  "HCP",
  "Other",
];

export const indianFamilyRelations = [
  "Self",
  "Father",
  "Mother",
  "Son",
  "Daughter",
  "Brother",
  "Sister",
  "Grandfather",
  "Grandmother",
  "Grandson",
  "Granddaughter",
  "Uncle",
  "Aunt",
  "Maternal Uncle",
  "Maternal Aunt",
  "Paternal Uncle",
  "Paternal Aunt",
  "Cousin Brother",
  "Cousin Sister",
  "Nephew",
  "Niece",
  "Father-in-law",
  "Mother-in-law",
  "Son-in-law",
  "Daughter-in-law",
  "Brother-in-law",
  "Sister-in-law",
  "Husband",
  "Wife",
  "Godfather",
  "Godmother"
];

export const medicalSpecializations = [
  "Cardiologist",
  "Dermatologist",
  "Neurologist",
  "Pediatrician",
  "Psychiatrist",
  "Psychologist",
  "Orthopedic Surgeon",
  "Gastroenterologist",
  "Ophthalmologist",
  "ENT Specialist",
  "Endocrinologist",
  "Gynecologist",
  "Obstetrician",
  "Pulmonologist",
  "Urologist",
  "Nephrologist",
  "Rheumatologist",
  "Oncologist",
  "Hematologist",
  "Immunologist",
  "Radiologist",
  "Pathologist",
  "General Surgeon",
  "Anesthesiologist",
  "Emergency Medicine Specialist",
  "Family Physician",
  "Internal Medicine Specialist",
  "Infectious Disease Specialist",
  "Plastic Surgeon",
  "Cosmetic Surgeon",
  "Osteopath",
  "Chiropractor",
  "Podiatrist",
  "Speech Therapist",
  "Physiotherapist",
  "Occupational Therapist",
  "Dentist",
  "Oral Surgeon",
  "Veterinarian"
];


export const physioSpecializations = [
  "Orthopedic Physiotherapy",
  "Neurological Physiotherapy",
  "Cardiopulmonary Physiotherapy",
  "Pediatric Physiotherapy",
  "Geriatric Physiotherapy",
  "Sports Physiotherapy",
  "Women's Health Physiotherapy",
  "Manual Therapy",
  "Electrotherapy",
  "Musculoskeletal Physiotherapy",
  "Post-Surgical Rehabilitation",
  "Spinal Cord Injury Rehabilitation",
  "Stroke Rehabilitation",
  "Pulmonary Rehabilitation",
  "Chronic Pain Management",
  "Occupational Physiotherapy",
  "Community Physiotherapy",
  "Acute Care Physiotherapy",
  "Balance and Vestibular Rehabilitation",
  "Pelvic Floor Physiotherapy"
];
export const PDRspecialityOptions = [
  'Neurological', 'Cardiological', 'Respiratory', 'Gastro', 'Surgery', 'Orthopedics', 'Other'
]

export const treatmentOptions = [
  'Medication', 'Hospital Visit', 'Physiotherapy', 'Nursing', 'Other'
]


export const mobilityAids = [
  'Crutches', 'Wheelchair', 'Frame', 'Eye Glasses', 'Footwear', 'Hearing Aids', 'Call bell', 'Walking stick'
]

export const breathingEquipments = [
  'CPAP', 'BIPAP', 'Home Oxygen', 'Nebuliser', 'Inhalers'
]

export const nutritionFeeds = [
  'Independent', 'Prompt', 'PEG Feed', 'NG Feed', 'AO1', 'Swallowing Issue', 'Diabetic'
]

export const hygieneOptions = [
  'Assistance Required', 'Independent', 'Supervised', 'Partially Dependent'
]

export const bedTypes = [
  'Functional', 'Normal', 'Side rails', 'Air Mattress', 'Movable', 'Lifted', 'Any other special'
]

export const floorTypes = [
  'Stone', 'Tiles', 'Wood', 'Carpet', 'Rubber', 'Polished/Slippery'
]

export const washroomAccessories = [
  'Bell', 'Side Rails', 'Door Open Locking', 'Grab Bars', 'Anti-skid Mat', 'Shower Chair'
]

export const administerBy = ["Family", "HCP", "Independent", "Other"]

export const Allergiesoptions = [
  "Vegan",
  "Egg",
  "Dairy",
  "Citrus",
  "Nuts",
  "Gluten"
];

export const mealTimings = [
  "Before Food",
  "Breakfast",
  "Mid Morning",
  "Lunch",
  "Dinner",
  "After Food"
];
export const DiabeticSpecifications = [
  "Type 1 Diabetes",
  "Type 2 Diabetes",
  "Gestational Diabetes",
  "Prediabetes",
  "Monogenic Diabetes (MODY / Neonatal)",
  "Secondary Diabetes"
]

export const FootItems = ["Tea", "Coffee", "Hot Water", "Boiled Egg", "Sabudana", "Kichidi", "Maggie", "Chapathi", "Rice", "Curry", "OtherItem"]

export const HygineOptions = ["Daily", "As Needed", "Alternate day"]

export const Vitals_Options = ["As Required", "Morning", "Afternoon", "Evening", "Specify Time"]

export const Mobility_excercise_Options = ["Repeat", "Hold each time", "Sets"]

export const Relations = [
  "Father",
  "Mother",
  "Brother",
  "Sister",
  "Grandfather",
  "Other"
];

export const HyderabadAreas = [
  "Banjara Hills",
  "Jubilee Hills",
  "Madhapur",
  "Gachibowli",
  "Kondapur",
  "Hitech City",
  "Ameerpet",
  "Begumpet",
  "Secunderabad",
  "Kukatpally",
  "Manikonda",
];

export const sampleData: any = {
  Balance: "No",
  Bathing: "Independent",
  Bedding: "Independent",
  Depression: "No",
  "Frequent Urination": "Yes",
  Grooming: "Independent",
  "Hand Wash": "Independent",
  "Hearing Loss": "Yes",
  "History of Fall": "No",
  "Mouth Care": "Assistance Required",
  "Nail Care": "Independent",
  "Room Hygiene": "Independent",
  "Sleep Issues": "Yes",
  Toileting: "Independent",
  "Visual Impairment": "No",
  administerBy: "Family",
  bedAssistance: "Yes",
  bedType: "Functional",
  breathingEquipment: "BIPAP",
  catheterDueDate: "2025-09-02",
  constipated: "No",
  dietType: "High Protein",
  eliminationSupport: "Bedpan",
  feedingMethod: "NG Feed",
  floorFallRisk: "Yes",
  floorType: "Stone",
  foodAllergy: "Test Food Allergy",
  hobbies: "Test Hobbies",
  hospitalVisits: "Test Hospital Visits",
  hydrationDisease: "Test Hydration",
  hydrationStatus: "Limit",
  mobility: "Independent",
  mobilityAid: "Crutches",
  occupation: "Test CurrentOccupation",
  presentIllness: "Test Illness",
  relation: "Test Relation",
  remarks: "ssdsd",
  speciality: "Cardiological",
  treatment: "Medication",
  washroomAccessory: "Bell",
  Medications: [
    {
      medicationName: "Test Medication",
      dose: "Test Dose",
      quantity: "5",
      route: "Test Route",
      administerBy: "",
    },
  ],
  Inputs: {
    personalFamilyRemark: "Test Remarks",
  },
};




export const VendorScreens: any = {
  "HCP Vendor": {
    mainTitle: "HCP vendor Form",
    sections: [
      {
        items: [
          "Vendor Name:",
          "Vendor Company Name:",
          "Registration ID:",
          "PAN:",
          "Phone:",
          "Email ID:",
          "Aadhar:",
          "Company PAN:",
          "Bank Name:",
          "Bank Account:",
          "IFSC Code:",
          "Branch Name:",
          "City:",
          "State:",
          "Username: Email ID",
          "Password:",
          "Mobile OTP Login:",
        ],
      },
      {
        title: "Terms and Conditions",
        items: [
          "Account maintenance charges 200/-",
          "Staff responsibility",
          "Payment to staff in time",
        ],
      },
    ],
  },

  "Business Vendor": {
    mainTitle: "Business Vendor Form",
    sections: [
      {
        items: [
          "Client Vendor Name:",
          "Organization Name:",
          "Organization Email ID:",
          "Client Vendor Email ID:",
          "Alternative Point of Contact:",
          "POC Contacts:",
          "POC Email IDs:",
          "Company Registration:",
          "PAN:",
          "Bank Name:",
          "Bank Account:",
          "IFSC Code:",
          "Branch Name:",
          "City:",
          "State:",
          "Username: Company Email ID",
          "Password:",
          "Mobile OTP Login:",
        ],
      },
      {
        title: "Terms and Conditions",
        items: ["Account maintenance charges 200/-"],
      },
    ],
  },

  Institute: {
    mainTitle: "Institute Vendor",
    sections: [
      {
        items: [
          "Institute Name:",
          "Institute email ID:",
          "Institute PAN ID:",
          "Institute Registration ID:",
          "Institute Point of Contacts:",
          "Primary Name:",
          "Contact:",
          "Secondary Name:",
          "Bank Name:",
          "Bank Account:",
          "IFSC Code:",
          "Branch Name:",
          "City:",
          "State:",
        ],
      },
      {
        title: "Terms and Conditions",
        items: [
          "Add option to add resources & documents",
          "Compliance report for resources",
          "Attendance only till referral period",
        ],
      },
    ],
  },

  "Individual Vendor": {
    mainTitle: "Individual Vendor",
    sections: [
      {
        items: [
          "Individual Vendor Name:",   // UPDATED
          "Contact:",
          "Aadhar:",
          "PAN:",
          "Bank Name:",
          "Bank Account:",
          "IFSC Code:",
          "Branch Name:",
          "City:",
          "State:",
        ],
      },
    ],
  },
};

export const VendorFieldMap: any = {
  // ========================
  // BASIC FIELDS
  // ========================
  "Vendor Name:": "VendorName",
  "Vendor Company Name:": "CompanyName",
  "Client Vendor Name:": "VendorName",
  "Institute Name:": "InstituteName",
  "Individual Vendor Name:": "VendorName",

  // EMAIL
  "Email ID:": "Email",
  "Organization Email ID:": "Email",
  "Client Vendor Email ID:": "Email",
  "Institute email ID:": "Email",
  "Contact: Email ID:": "Email",
  "Username: Company Email ID": "Email",
  "Username: Email ID": "Email",

  // PHONE
  "Phone:": "ContactNumber",
  "POC Contacts:": "ContactNumber",
  "Contact:": "ContactNumber",

  // PAN / AADHAR
  "PAN:": "PANNumber",
  "Aadhar:": "AadharNumber",
  "Institute PAN ID:": "PANNumber",

  // BANK DETAILS
  "Bank Name:": "BankName",
  "Bank Account:": "BankAccount",
  "IFSC Code:": "IFSC",
  "Branch Name:": "BankBranch",

  // LOCATION
  "City:": "City",
  "State:": "State",

  // ========================
  // ATTACHMENTS (YOUR 4 FINAL ONES)
  // ========================
  "Bank Proof Attachment": "BankProofURL",
  "Company PAN Attachment": "CompanyPANAttachmentURL",
  "PAN Attachment": "PANAttachmentURL",
  "Aadhar Attachment": "AadharAttachmentURL",

  // PASSWORD
  "Password:": "Password",
  "Mobile OTP Login:": "MobileOTP",
};

export const columns = [
  "StartDate",
  "EndDate",
  "VendorName",
  "OrganisationName",
  "Contact",
  "Price",
  "Attendence",
];


export const indianStates = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal"
];



export const Infodata = [
  {
    Month: "March",
    DaysInMonth: "1st to 15th",
    VendorName: "D.Prasad",

    ResourceAcquired: "Katta Venkateshwar Rao",
    OrganisationName: "Carefirst",

    Price: 8910,
    StartDate: "01/03/2024",
    EndDate: "15/03/2024",

  }
];

   export const company = {
        name: 'Curate Health Services LLP',
        addressLines: [
            '15/100030, Brindhavanam Colony',
            'Near Iskabavi',
            'Beeramguda Telangana 502032',
            'India',
        ],
        website: 'www.curatehealthservices.com',
        logoUrl: '/logo.png',
        notes: 'A Complete Home Healthcare Professionals. We care for your beloved.'
    };

  export const payment = {
    accountName: "Curate Health Services",
    accountNumber: "01140210002278",
    BankName: "UCO Bank",
    ifsc: "UCBA0000114",
    upiId: "curateservices@ucobank",
  };

export const terms = [
'Advance payment for 7 days has to be paid immediately after accepting the service.',
'Termination should be informed before 5 days, if not 5 days charges will be added to the service invoice. (This is due to sudden loss of job for healthcare professional).',
'Replacement charges will be applied, if the operational cost is not feasible to adjust with the service provided.',
'Payment is accepted online to the bank account or UPI scanning. No cash receipts, cash collection deposit will have additional charges of 250/-.',
'Late payment charges are collected with 500/- for every 7 days overdue.',
'Refund policy is to clear within 7 days, deducting any additional charges and cancellations with the service provided or consumed. There is no refund for medical equipment and services consumed when delivered.',
'Confidential Clause: Patient details mentioned in the invoice are confidential and intended solely for billing purposes.',
'No Liability Disclaimer: Company is not liable for any direct or indirect consequential losses arising from healthcare services provided by contractor. Service provider and company are two different entities.',
'TDS is applicable as per IT Act and FORM 16A.',
'This is an E-invoice, this computer-generated invoice does not require a signature.',
'Acknowledgement Clause: Receipt of this invoice confirms that services were availed as per patient consent.',
'All billing enquiries must be mailed to info@curatehealth.in to be addressed accordingly.',
'Client service agreement has more detailed information on payment terms'
];



export const IndianLanguages = [
  "Assamese", "Bengali", "Bodo", "Dogri", "Gujarati", "Hindi", "Kannada",
  "Kashmiri", "Konkani", "Maithili", "Malayalam", "Manipuri", "Marathi",
  "Nepali", "Odia", "Punjabi", "Sanskrit", "Santali", "Sindhi", "Tamil",
  "Telugu", "Urdu",
  "Tulu", "Khasi", "Garo", "Mizo", "Nagamese", "Ladakhi", "Bhil",
  "Rajasthani", "Haryanvi", "Bhojpuri", "Chhattisgarhi", "Garhwali",
  "Kumaoni", "Sourashtra"
];

export const HomeAssistance = [
  "Brushing",
  "Face cleaning",
  "Diaper changing",
  "Bathing (Bed Bath or Sponge Bath)",
  "Hair washing",
  "Patient cloth washing through machine",
  "Dressing & Grooming",
  "Bed Making",
  "Washroom assistance",
  "Walker or Stick assistance for exercise",
  "Wheelchair activities",
  "Artificial commode activities",
  "Giving bed pan",
  "Urine bottle emptying",
  "Stoma bag care",
  "Catheter care",
  "NG tube feeding (Ryles tube feeding)",
  "Diabetic care",
  "Basic nursing activities (Vital signs)",
  "Temperature checking",
  "Pulse checking",
  "Blood pressure checking",
  "Glucose (Sugar) checking",
  "Oxygen (Saturation) checking",
  "Medications",
  "Nebulization",
  "Handling oxygen concentrator",
  "Bedding",
  "Small injury dressing",
  "Small food preparation for patient (e.g., Maggie, boiled egg, hot water, tea, coffee, daliya, khichdi, sabudana etc.)"
];


export const patientCategories = [
  "Independent Patients",
  "Support Care Patients",
  "Wheel Chair - self propel",
  "Wheel Chair - Dependent",
  "Semi Bedridden - Limited Mobility",
  "Completely Bedridden",
  "Paralysis/Stroke Patients",
  "Post Surgery care",
  "Fractures/Injury"
];


export const PatientTypes=[ "Independent Patients",
  "Support Care Patients",
  "Wheel Chair - self propel",
  "Wheel Chair - Dependent",
  "Semi Bedridden - Limited Mobility",
  "Completely Bedridden",
  "Paralysis/Stroke Patients",
  "Post Surgery care",
  "Fractures/Injury",
  "Other"

]

export const IndianStates = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal"
];
export const IndianCapitalCities = [
  "Amaravati",
  "Itanagar",
  "Dispur",
  "Patna",
  "Raipur",
  "Panaji",
  "Gandhinagar",
  "Chandigarh",
  "Shimla",
  "Ranchi",
  "Bengaluru",
  "Thiruvananthapuram",
  "Bhopal",
  "Mumbai",
  "Imphal",
  "Shillong",
  "Aizawl",
  "Kohima",
  "Bhubaneswar",
  "Jaipur",
  "Gangtok",
  "Chennai",
  "Hyderabad",
  "Agartala",
  "Lucknow",
  "Dehradun",
  "Kolkata",
  "Port Blair",
  "New Delhi",
  "Daman",
  "Leh",
  "Kavaratti",
  "Puducherry",
  "Srinagar",
  "Jammu",
  "Other"
];




export const NURSE_SPECIALTIES: string[] = [
  "General Nursing",
  "ICU Care",
  "Emergency Care",
  "Post-Operative Care",
  "Geriatric (Elderly) Care",
  "Palliative Care",
  "Wound & Bedsore Care",
  "Diabetes Care",
  "Cardiac Care",
  "Respiratory Care",
  "Ventilator Care",
  "Tracheostomy Care",
  "Catheter Care",
  "IV Therapy",
  "Injection Administration",
  "Medication Management",
  "Pain Management",
  "Mother & Baby Care",
  "Home Nursing",
];
export const NURSE_TYPES: string[] = [
  "General Nurse (GNM)",
  "Auxiliary Nurse Midwife (ANM)",
  "Registered Nurse (RN)",
  "Staff Nurse",
  "ICU Nurse",
  "Home Care Nurse",
  "Pediatric Nurse",
  "Geriatric Nurse",
  "Psychiatric Nurse",
  "Community Health Nurse",
  "Critical Care Nurse",
  "Emergency Nurse",
  "Midwife",
];

export const Patient_Home_Supply_Needs=[
  "Diaper",
  "Cervical collars",
  "Walker",
  "Wheel chair",
  "Artificial Comode",
  "Hospital Bed",
  "Wet wipes",
  "Cotton",
  "Medication store box",
  "Lumber (back) Belt",
  "Glucose machine",
  "Automatic Blood pressure monitor",
  "Hand Gloves",
  "Garbage Bag",
  "Face Mask",
  "Medications",
  "Under Pads",
  "Water mattress",
  "Air Mattress",
  "First Aid kit",
  "Rubber Sheet",
  "Hand wash",
  "Sanitizer bottle",
  "Nebilizer machine",
  "Steam Inhaler machine",
  "Instant cold pack"
]



export const Health_Card = [
  "Diabetes Mellitus",
  "Hypertension",
  "Dementia",
  "Parkinson's Disease",
  "Stroke / Paralysis",
  "Alzheimer's Disease",
  "Chronic Kidney Disease (CKD)",
  "Chronic Obstructive Pulmonary Disease (COPD)",
  "Heart Attack",
  "Post Cardiac Surgery",
  "Thyroid",
  "Obesity",
  "Urinary Incontinence",
  "Liver Disease",
  "Hepatitis",
  "Colostomy Patients",
  "Osteoarthritis",
  "Rheumatoid Arthritis",
  "Post Orthopedic Surgeries - Hip/Knee Replacement, Spine Surgery",
  "Cancers",
  "Palliative Care - End of Life Care",
  "Geriatric Patients"
];

export const paymentData = [
 {
    typeOfPayment: "Payment of contractors HUF/Individual (Reduced)",
    taxType: "TDS",
    section: "194C",
    tdsRate: "0.75%"
  },
  {
    typeOfPayment: "Payment of contractors HUF/Individual",
    taxType: "TDS",
    section: "194C",
    tdsRate: "1%"
  },
  {
    typeOfPayment: "Payment of contractors for Others (Reduced)",
    taxType: "TDS",
    section: "194C",
    tdsRate: "1.5%"
  },
  {
    typeOfPayment: "Payment of contractors for Others",
    taxType: "TDS",
    section: "194C",
    tdsRate: "2%"
  },
  {
    typeOfPayment: "Professional Fees (10%)",
    taxType: "TDS",
    section: "194J",
    tdsRate: "10%"
  },
    {
    typeOfPayment: "Professional Fees (1%)",
    taxType: "TDS",
    section: "194J",
    tdsRate: "1%"
  },
    {
    typeOfPayment: "Professional Fees (2%)",
    taxType: "TDS",
    section: "194J",
    tdsRate: "2%"
  },
  {
    typeOfPayment: "Professional Fees (Reduced)",
    taxType: "TDS",
    section: "194J",
    tdsRate: "7.5%"
  },
  {
    typeOfPayment: "Commission or Brokerage",
    taxType: "TDS",
    section: "194H",
    tdsRate: "5%"
  },
  {
    typeOfPayment: "Commission or Brokerage (Reduced)",
    taxType: "TDS",
    section: "194H",
    tdsRate: "3.75%"
  },
  {
    typeOfPayment: "Dividend",
    taxType: "TDS",
    section: "194",
    tdsRate: "10%"
  },
  {
    typeOfPayment: "Dividend (Reduced)",
    taxType: "TDS",
    section: "194",
    tdsRate: "7.5%"
  },
  {
    typeOfPayment: "Other Interest than securities",
    taxType: "TDS",
    section: "194A",
    tdsRate: "10%"
  },
  {
    typeOfPayment: "Other Interest than securities (Reduced)",
    taxType: "TDS",
    section: "194A",
    tdsRate: "7.5%"
  },
  {
    typeOfPayment: "Rent on land or furniture etc",
    taxType: "TDS",
    section: "194I",
    tdsRate: "10%"
  }
];



export  const serviceOptions = [
  { name: "Healthcare Assistant Service", code: "HCAS", amount: 20000 },
  { name: "Nursing Care Service", code: "NURS", amount: 35000 },
  { name: "Bedside Attendant", code: "BSA", amount: 15000 }
];


export const hyderabadAreas = [
  "Banjara Hills",
  "Jubilee Hills",
  "HITEC City",
  "Gachibowli",
  "Madhapur",
  "Kukatpally",
  "Ameerpet",
  "Begumpet",
  "Somajiguda",
  "Secunderabad",
  "Mehdipatnam",
  "Miyapur",
  "Manikonda",
  "Uppal",
  "Nallakunta",
  "Chandanagar",
  "Nampally",
  "Abids",
  "Ashok Nagar",
  "Asif Nagar",
  "Bahadurpura",
  "Aliabad",
  "Aghapura",
  "Sainikpuri",
  "Amberpet",
  "Badichowdi",
  "Balkampet",
  "Barkatpura",
  "Bagh Lingampally",
  "Adikmet",
  "Koti",
  "Tolichowki",
  "Dilsukhnagar",
  "LB Nagar",
  "Himayat Nagar",
  "Khairatabad",
  "Kondapur",
  "Nizampet",
  "Shamshabad",
  "Medchal",
  "Tellapur",
  "Narsingi"
];

export const EducationLevels = [
  "10th (Secondary School)",
  "12th (Higher Secondary)",
  "ITI",
  "Diploma",
  "Under Graduate (UG)",
  "Post Graduate (PG)",
  "Other"
];


export const StaffEmails = [
  "admin@curatehealth.in",
  "tsiddu805@gmail.com",
  "panducurate@gmail.com",
  "info@curatehealth.in",
  "gouricurate@gmail.com",
  "kirancuratehealth@gmail.com",
  "srivanikasham@curatehealth.in",
  "sravanthicurate@gmail.com",
  "srinivasnew0803@gmail.com",
  "rpandu823@gmail.com",
]


export const Departments = [
  "Operations",
  "Training",
  "Marketing",
  "Accounting and Finance",
  "Management",
  "Directorship",
  "Other",
];



export const JobTitles = [
  "Operations Executive",
  "Business Executive",
  "Senior Operations & Business",
  "Senior Business and Operations",
  "Senior Operations",
  "Training",
  "Senior Training",
  "Accounting and Finance Executive",
  "Other",
];
