import { title } from "process";

export const medicalSpecialties = [

  "General Physician",
  "Cardiologist",
  "Dermatologist",
  "Pediatrician",
  "Gynecologist",
  "Orthopedic Surgeon",
  "Psychiatrist",
  "ENT Specialist",
  "Neurologist",
  "Ophthalmologist",
  "Dentist",
  "Oncologist",
  "Urologist",
  "Gastroenterologist",
  "Nephrologist",
  


  "Registered Nurse (RN)",
  "Nurse Practitioner (NP)",
  "Critical Care Nurse (ICU Nurse)",
  "Pediatric Nurse",
  "Emergency Room Nurse (ER Nurse)",
  "Surgical Nurse",
  "Labor and Delivery Nurse",
  "Neonatal Nurse (NICU Nurse)",
  "Home Health Nurse",
  "Community Health Nurse",
  "Psychiatric Nurse",
  "Oncology Nurse",
  "Geriatric Nurse",
  "Travel Nurse",
  "Public Health Nurse",
  "Occupational Health Nurse",
  "School Nurse"
];



export const HYDERABAD_LOCATIONS = [
  "Banjara Hills", "Jubilee Hills", "Gachibowli", "Hitech City", "Madhapur", "Manikonda",
  "Begumpet", "Ameerpet", "Kukatpally", "Secunderabad", "Kondapur", "Miyapur",
  "Mehdipatnam", "Somajiguda", "Dilsukhnagar", "LB Nagar", "Tolichowki", "Kompally",
  "Uppal", "Nallagandla", "Attapur", "Khairatabad", "Panjagutta", "Yousufguda",
  "Erragadda", "SR Nagar", "Moosapet", "RTC X Roads", "Basheerbagh", "Koti",
  "Abids", "Himayatnagar", "Chikkadpally", "Musheerabad", "Amberpet", "Nagole",
  "Charminar", "Malakpet", "Bahadurpura", "Shamshabad", "Rajendra Nagar", "Alwal",
  "ECIL", "Malkajgiri", "Nacharam", "Peerzadiguda", "Hayathnagar",
  "Gandipet", "Patancheru", "Isnapur", "Tellapur", "Tarnaka", "Habsiguda", "Moosarambagh",
  "Sainikpuri", "Bowenpally", "Nizampet", "Bachupally", "Chandanagar", "Beeramguda"
];


// export const All_Medical_Colleges_Names=[
//   "Andaman & Nicobar Islands Institute of Medical Sciences, Port Blair (Andaman Nicobar Islands)",
//   "Alluri Sitharam District Government Medical College, Paderu (Andhra Pradesh)",
//   "Government Medical College, Machilipatnam (Andhra Pradesh)",
//   "ACSR Government Medical College, Nellore (Andhra Pradesh)",
//   "All India Institute of Medical Sciences, Mangalagiri, Vijayawada (Andhra Pradesh)",
//   "Alluri Sitaram Raju Academy of Medical Sciences, Eluru (Andhra Pradesh)",
//   "Andhra Medical College, Visakhapatnam (Andhra Pradesh)",
//   "Apollo Institute of Medical Sciences and Research, Chittoor (Andhra Pradesh)",
//   "Dr. P.S.I. Medical College, Chinoutpalli (Andhra Pradesh)",
//   "Fathima Instt. of Medical Sciences, Kadapa (Andhra Pradesh)",
//   "Gayathri Vidya Parishad Institute of Health Care & Medical Technology, Visakhapatnam (Andhra Pradesh)",
//   "Gandhi Institute of Technology and Management (GITAM University) Deemed, Visakhapatnam (Andhra Pradesh)",
//   "Government Medical College, Ananthapuram (Andhra Pradesh)",
//   "Government Medical College, Eluru (Andhra Pradesh)",
//   "Government Medical College, Nandyal (Andhra Pradesh)",
//   "Government Medical College, Rajamahendravaram (Andhra Pradesh)",
//   "Government medical college, vizianagaram (Andhra Pradesh)",
//   "Government Siddhartha Medical College, Vijaywada (Andhra Pradesh)",
//   "Great Eastern Medical School and Hospital, Srikakulam (Andhra Pradesh)",
//   "GSL Medical College, Rajahmundry (Andhra Pradesh)",
//   "Guntur Medical College, Guntur (Andhra Pradesh)",
//   "Katuri Medical College, Guntur (Andhra Pradesh)",
//   "Konaseema Institute of Medical Sciences & Research Foundation, Amalapuram (Andhra Pradesh)",
//   "Kurnool Medical College, Kurnool (Andhra Pradesh)",
//   "Maharajah Institute of Medical Sciences, Vizianagaram (Andhra Pradesh)",
//   "Narayana Medical College, Nellore (Andhra Pradesh)",
//   "Nimra Institute of Medical Sciences, Krishna Dist. (Andhra Pradesh)",
//   "NRI Institute of Medical Sciences, Visakhapatnam (Andhra Pradesh)",
//   "NRI Medical College, Guntur (Andhra Pradesh)",
//   "PES Institute Of Medical Sciences and Research, Kuppam (Andhra Pradesh)",
//   "Rajiv Gandhi Institute of Medical Sciences, Kadapa (Andhra Pradesh)",
//   "Rajiv Gandhi Institute of Medical Sciences, Ongole (Andhra Pradesh)",
//   "Rajiv Gandhi Institute of Medical Sciences, Srikakulam (Andhra Pradesh)",
//   "Rangaraya Medical College, Kakinada (Andhra Pradesh)",
//   "SV Medical College, Tirupati (Andhra Pradesh)",
//   "Santhiram Medical College, Nandyal (Andhra Pradesh)",
//   "Sri Balaji Medical College, Hospital and Research Instiutute, Chittoor (Andhra Pradesh)",
//   "SVIMS-Sri Padmavathi Medical College for Women, Alipiri Road, Tirupati (Andhra Pradesh)",
//   "Viswabharathi Medical College (Andhra Pradesh)",
//   "Tomo Riba Institute of Health & Medical Sciences, Naharlagun (Arunachal Pradesh)",
//   "Tinsukia Medical College - Assam Pin-786146 (Assam)",
//   "Nalbari Medical College, Nalbari (Assam)",
//   "Gauhati Medical College, Guwahati (Assam)",
//   "All India Institute of Medical Sciences (AIIMS), Guwahati (Assam)",
//   "Silchar Medical College, Silchar (Assam)",
//   "Jorhat Medical College & Hospital, Jorhat (Assam)",
//   "Assam Medial College, Dibrugarh (Assam)",
//   "Lakhimpur Medical College (Assam)",
//   "Diphu Medical College & Hospital, Diphu, Assam (Assam)",
//   "Tezpur Medical College & Hospital, Tezpur (Assam)",
//   "Nagaon Medical College (Assam)",
//   "Kokrajhar Medical College (Assam)",
//   "Dhubri Medical College, Dhubri (Assam)",
//   "Fakhruddin Ali Ahmed Medical College, Barpeta, Assam (Assam)",
//   "Himalaya Medical College and Hospital, Patna, Bihar (Bihar)",
//   "Government Medical College, Purnea (Bihar)",
//   "Mata Gujri Memorial Medical College, Kishanganj (Bihar)",
//   "Patna Medical College, Patna (Bihar)",
//   "Darbhanga Medical College, Lehriasarai (Bihar)",
//   "Katihar Medical College, Katihar (Bihar)",
//   "All India Institute of Medical Sciences, Patna (Bihar)",
//   "Nalanda Medical College, Patna (Bihar)",
//   "Shri Krishna Medical College, Muzzafarpur (Bihar)",
//   "Jawaharlal Nehru Medical College, Bhagalpur (Bihar)",
//   "Anugrah Narayan Magadh Medical College, Gaya (Bihar)",
//   "Radha Devi Jageshwari Memorial Medical College land Hospital (Bihar)",
//   "Shree Narayan Medical Institute and Hospital (Bihar)",
//   "Employees State Insurance Corporation Medical College, Patna (Bihar)",
//   "Jannayak Karpoori Thakur Medical College & Hospital, Madhepura, Bihar (Bihar)",
//   "Netaji Subhas Medical College & Hospital, Amhara, Bihta, Patna (Bihar)",
//   "Lord Buddha Koshi Medical College and Hospital, Saharsa (Bihar)",
//   "Madhubani Medical College, Madhubani (Bihar)",
//   "Government Medical College, Bettiah (Bihar)",
//   "Vardhman Institute of Medical Sciences, Pawapuri, Nalanda (Bihar)",
//   "Indira Gandhi Institute of Medical Sciences, Sheikhpura, Patna (Bihar)",
//   "Narayan Medical College & Hospital, Sasaram (Bihar)",
//   "Government Medical College, Chandigarh (Chandigarh)",
//   "Abhishek Mishra Memorial Medical College & RC Bhiali Distt. Durg CG (Chattisgarh)",
//   "Shri Rawatpura Sarkar Institute of Medical Sciences and Research Atal Nagar, Dist- Raipur (C.G.) (Chattisgarh)",
//   "Late Shri Baliram Kashyap Memorial NDMC Govt. Medical College, Jagdalpur (Chattisgarh)",
//   "All India Institute of Medical Sciences, Raipur (Chattisgarh)",
//   "Government Medical College, Kanker (Chattisgarh)",
//   "Pt. J NM Medical College, Raipur (Chattisgarh)",
//   "Chhattisgarh Institute of Medical Sciences, Bilaspur (Chattisgarh)",
//   "Shri Balaji Institute of Medical Science (Chattisgarh)",
//   "Raipur Institute of Medical Sciences (RIMS), Raipur (Chattisgarh)",
//   "Shri Shankaracharya Institute of Medical Sciences, Bhilai (Chattisgarh)",
//   "Government Medical College, Ambikapur (Surguja), Chhattisgarh (Chattisgarh)",
//   "Government Medical College, Mahasamund (Chattisgarh)",
//   "Government Medical College, Korba (Chattisgarh)",
//   "Government Medical College (Bharat Ratna Shri Atal Bihari Vajpyee Memorial Med. Col.), Rajnandgaon (Chattisgarh)",
//   "Chandulal Chandrakar Memorial Medical College, Durg (Chattisgarh)",
//   "Late Shri Lakhi Ram Agrawal Memorial Govt. Medical College, Raigarh (Chattisgarh)",
//   "NAMO Medical Education and Research Institute, Silvassa (Dadra and Nagar Haveli)",
//   "Vardhman Mahavir Medical College & Safdarjung Hospital, Delhi (Delhi)",
//   "Army College of Medical Sciences, New Delhi (Delhi)",
//   "All India Institute of Medical Sciences, New Delhi (Delhi)",
//   "University College of Medical Sciences & GTB Hospital, New Delhi (Delhi)",
//   "Lady Hardinge Medical College, New Delhi (Delhi)",
//   "Maulana Azad Medical College, New Delhi (Delhi)",
//   "Atal Bihari Vajpayee Institute of Medical Sciences and Dr. RML Hospital, New Delhi (Delhi)",
//   "Dr. Baba Saheb Ambedkar Medical College, Rohini, Delhi (Delhi)",
//   "North Delhi Muncipal Corporation Medical College, Delhi (Delhi)",
//   "Hamdard Institute of Medical Sciences & Research, New Delhi (Delhi)",
//   "Goa Medical College, Panaji (Goa)",
//   "Bhagyoday Medical College (Gujarat)",
//   "SAL Institute of Medical Sciences, Ahmedabad (Gujarat)",
//   "SWAMIINARAYAN INSTITUTE OF MEDICAL SCIENCES & RESEARCH (Gujarat)",
//   "All India Institute of Medical Science, Rajkot (Gujarat)",
//   "Surat Municipal Institute of Medical Education & Research, Surat (Gujarat)",
//   "MP Shah Medical College, Jamnagar (Gujarat)",
//   "BJ Medical College, Ahmedabad (Gujarat)",
//   "Pandit Deendayal Upadhyay Medical College, Rajkot (Gujarat)",
//   "SBKS Medical Instt. & Research Centre, Vadodra (Gujarat)",
//   "CU Shah Medical College, Surendra Nagar (Gujarat)",
//   "Government Medical College, Bhavnagar (Gujarat)",
//   "Medical College, Baroda (Gujarat)",
//   "Smt. N.H.L.Municipal Medical College, Ahmedabad (Gujarat)",
//   "Government Medical College, Surat (Gujarat)",
//   "Dr. Kiran C.Patel Medical College and Research Institute (Gujarat)",
//   "Shantabaa Medical College, Amreli (Gujarat)",
//   "Nootan Medical College and Research Centre, Mehsana (Gujarat)",
//   "Dr. N.D. Desai Faculty of Medical Science and Research, Nadiad (Gujarat)",
//   "Kiran Medical College (Gujarat)",
//   "Zydus Medical College & Hospital, Dahod (Gujarat)",
//   "Banas Medical College and Research Institute, Palanpur, Gujarat (Gujarat)",
//   "GMERS Medical College, Vadnagar, Mehsana (Gujarat)",
//   "Dr. M.K. Shah Medical College & Research Centre, Ahmedabad (Gujarat)",
//   "Parul Institute of Medical Sciences & Research, Vadodara (Gujarat)",
//   "GMERS Medical College, Hadiyol, Himmatnagar (Gujarat)",
//   "GMERS Medical College, Junagadh (Gujarat)",
//   "GMERS Medical College, Valsad (Gujarat)",
//   "GMERS Medical College, Dharpur Patan (Gujarat)",
//   "GMERS Medical College, Gandhinagar (Gujarat)",
//   "GCS Medical College, Ahmedabad (Gujarat)",
//   "GMERS Medical College, Gotri, Vadodara (Gujarat)",
//   "GMERS Medical College, Sola, Ahmedabad (Gujarat)",
//   "Gujarat Adani Institute of Medical Sciences, Bhuj (Gujarat)",
//   "Ahmedabad Municipal Coporation Medical Education Trust Medical College, Ahmedabad (Gujarat)",
//   "Government Medical College, Morbi (Gujarat)",
//   "Government Medical College, Navsari (Gujarat)",
//   "Ananya College of Medicine & Research, Kalol (Gujarat)",
//   "Government Medical College, Panchmahal Godhra (Gujarat)",
//   "Government Medical College, Porbandar (Gujarat)",
//   "GMERS Medical College, Rajpipla (Gujarat)",
//   "Pramukhswami Medical College, Karmsad (Gujarat)",
//   "Maharishi Markandeshwar College of Medical Sciences & Research, Sadopur (Haryana)",
//   "Amrita School of Medicine, Faridabad (Haryana)",
//   "Maharaja Agrasen Medical College, Agroha (Haryana)",
//   "Faculty of Medicine and Health Sciences, Gurgaon (Haryana)",
//   "Pt. B D Sharma Postgraduate Institute of Medical Sciences, Rohtak (Haryana)",
//   "Maharishi Markandeshwar Institute Of Medical Sciences & Research, Mullana, Ambala (Haryana)",
//   "Al Falah School of Medical Sciences & Research Centre, Faridabad (Haryana)",
//   "Kalpana Chawala Govt. Medical College, Karnal, Haryana (Haryana)",
//   "Adesh Medical College and Hospital, Shahabad, Kurukshetra, Haryana (Haryana)",
//   "N.C. Medical College & Hospital, Panipat (Haryana)",
//   "World College of Medical Sciences & Researc, Jhajjar, Haryana (Haryana)",
//   "Employees State Insurance Corporation Medical College, Faridabad (Haryana)",
//   "Shaheed Hasan Khan Mewati Government Medical College, Nalhar (Haryana)",
//   "Shri Atal Bihari Vajpayee Government Medical College, Faridabad (Haryana)",
//   "BPS Government Medical College for Women, Sonepat (Haryana)",
//   "Indira Gandhi Medical College, Shimla (Himachal Pradesh)",
//   "All india Institute of Medical Sciences, Bilaspur (Himachal Pradesh)",
//   "Dr. Radhakrishnan Government Medical College, Hamirpur, H.P (Himachal Pradesh)",
//   "Pt. Jawahar Lal Nehru Government Medical College, Chamba (Himachal Pradesh)",
//   "Shri Lal Bahadur Shastri Government Medical College, Mandi, HP (Himachal Pradesh)",
//   "Government Medical College, Nahan, Sirmour H.P. (Himachal Pradesh)",
//   "Maharishi Markandeshwar Medical College & Hospital, Solan (Himachal Pradesh)",
//   "Dr. Rajendar Prasad Government Medical College, Tanda, H.P (Himachal Pradesh)",
//   "Government Medical College Udhampur (Jammu & Kashmir)",
//   "Government Medical College Handwara (Jammu & Kashmir)",
//   "All India Institute of Medical Science, Vijaypur (Jammu & Kashmir)",
//   "Government Medical College, Jammu (Jammu & Kashmir)",
//   "Government Medical College, Srinagar (Jammu & Kashmir)",
//   "Sher-I-Kashmir Instt. Of Medical Sciences, Srinagar (Jammu & Kashmir)",
//   "Govt. Medical College, Doda. Kashmir (Jammu & Kashmir)",
//   "Government Medical College, Rajouri, J&K (Jammu & Kashmir)",
//   "Government Medical College, Kathua (Jammu & Kashmir)",
//   "Government Medical College, Baramulla (Jammu & Kashmir)",
//   "Government Medical College Anantnag (Jammu & Kashmir)",
//   "Acharya Shri Chander College of Medical Sciences, Jammu (Jammu & Kashmir)",
//   "MG M Medical College, Jamshedpur (Jharkhand)",
//   "All India Institute of Medical Sciences, Deoghar (Jharkhand)",
//   "Shaheed Nirmal Mahto Medical College & Hospital, Dhanbad (Jharkhand)",
//   "Mahadev Lal Goverment Medical College, Madhubani (Bihar)",
//   "BGS Global Institute of Medical Sciences, Bangalore (Karnataka)",
//   "Subbaiah Institute of Medical Sciences, Shimoga, Karnataka (Karnataka)",
//   "Employees State Insurance Corporation Medical College, Bangalore (Karnataka)",
//   "Srinivas Institute of Medical Research Centre, Srinivasnagar, Mangalore (Karnataka)",
//   "Sree Gokulam Medical College Trust & Research Foundation, Trivandrum (Kerala)",
//   "Travancore Medical College, Kollam (Kerala)",
//   "Sree Narayana Instt. of Medical Sciences, Chalakka, Ernakulam (Kerala)",
//   "Government Medical College, Kozhikode, Calicut (Kerala)",
//   "Malankara Orthodox Syrian Church Medical College, Kolenchery (Kerala)",
//   "Government Medical College, Konni (Kerala)",
//   "Government Medical College, Idukki (Kerala)",
//   "Pushpagiri Institute Of Medical Sciences and Research Centre, Tiruvalla (Kerala)",
//   "Government Medical College, Chhindwara, MP (Madhya Pradesh)",
//   "Government Medical College, Shahdol, MP (Madhya Pradesh)",
//   "Government Medical College, Shivpuri, MP (Madhya Pradesh)",
//   "Government Medical College, Ratlam (Madhya Pradesh)",
//   "Government Medical college and District Hospital, Ratnagiri (Maharashtra)",
//   "Mahatma Gandhi Mission Medical College, Vashi (Maharashtra)",
//   "Government Medical College, Parbhani (Maharashtra)",
//   "Parbhani Medical College (Maharashtra)",
//   "Indira Gandhi Medical College & Hospital, Nagpur (Maharashtra)",
//   "Rajiv Gandhi Medical College and Chhatrapati Shivaji Maharaj Hospital, Thane (Maharashtra)",
//   "Dr Vaishampayan Memorial Medical College, Solapur (Maharashtra)",
//   "ACPM Medical College, Dhule (Maharashtra)",
//   "Dr. Vasantrao Pawar Med. Col. Hosp. & Research Centre, Nasik (Maharashtra)",
//   "Bharatratna Atal Bihari Vajpayee Medical College, Pune (Maharashtra)",
//   "Government Medical College, Sindhudurg (Maharashtra)",
//   "Dr. N Y Tasgaonkar Institute of Medical Science Karjat (Maharashtra)",
//   "Mahatma Gandhi Missions Medical College, Navi Mumbai (Maharashtra)",
//   "Government Medical College, Osmanabad (Maharashtra)",
//   "Dr. Rajendra Gode Medical College, Amravati (Maharashtra)",
//   "Bharati Vidyapeeth University Medical College, Pune (Maharashtra)",
//   "Saheed Laxman Nayak Medical College & Hospital, Koraput (Orissa)",
//   "Hi-Tech Medical College & Hospital, Rourkela (Orissa)",
//   "Instt. Of Medical Sciences & SUM Hospital, Bhubaneswar (Orissa)",
//   "Government Medical College, Sundargarh (Orissa)",
//   "All India Institute of Medical Sciences, Bhatinda (Punjab)",
//   "Government Medical College, Patiala (Punjab)",
//   "Government Medical College, Amritsar (Punjab)",
//   "Adesh Institute of Medical Sciences & Research, Bhatinda (Punjab)",
//   "Dr B R Ambedkar State Institute of Medical Sciences, SAS Nagar , Mohali (Punjab)",
//   "Chintpurni Medical College, Pathankot, Gurdaspur (Punjab)",
//   "Punjab Institute of Medical Sciences, Jalandhar (Punjab)",
//   "Government Medical College, Jhunjhunu (Rajasthan)",
//   "Sudha Medical College, Kota, Rajasthan (Rajasthan)",
//   "Vyas Medical College & Hospital Jodhpur, Rajasthan (Rajasthan)",
//   "Government Medical College, Baran (Rajasthan)",
//   "Government Medical College, Nagaur (Rajasthan)",
//   "Government Medical College, Banswara (Rajasthan)",
//   "JIET Medical College and Hospital Jodhpur (Rajasthan)",
//   "K A P Viswanathan Government Medical College, Trichy (Tamil Nadu)",
//   "Sri Ramachandra Medical College & Research Institute, Chennai (Tamil Nadu)",
//   "KanyaKumari Government Medical College, Asaripallam (Tamil Nadu)",
//   "Faculty of Medicine , Sri Lalithambigai Medical College and Hospital Chennai (Tamil Nadu)",
//   "VELS Medical College & Hospital Tiruvallur (Tamil Nadu)",
//   "Government Medical College, Dindigul (Tamil Nadu)",
//   "Annapoorna Medical College & Hospital, Salem (Tamil Nadu)",
//   "Dhanalakshmi Srinivasan Medical College and Hospital, Perambalur (Tamil Nadu)",
//   "Government Villupuram Medical College, Villupuram (Tamil Nadu)",
//   "Thiruvarur Govt. Medical College, Thiruvarur (Tamil Nadu)",
//   "Government Medical College, Karimnagar (Telangana)",
//   "GOVERNMENT MEDICAL COLLEGE VIKARABAD (Telangana)",
//   "GOVERNMENT MEDICAL COLLEGE KHAMMAM (Telangana)",
//   "NEELIMA INSTITUTE OF MEDICAL SCIENCES (Telangana)",
//   "Surabhi Institute of Medical Sciences, Siddipet, Telangana (Telangana)"
// ]



// export const All_Medical_Colleges_Names = [
 
//   "Osmania Medical College, Hyderabad",
//   "Gandhi Medical College, Secunderabad",
//   "Kakatiya Medical College, Warangal",
//   "Government Medical College, Nizamabad",
//   "Government Medical College, Mahabubnagar",
//   "Government Medical College, Siddipet",
//   "Government Medical College, Suryapet",
//   "Government Medical College, Nalgonda",
//   "Government Medical College, Adilabad",
//   "Apollo Institute of Medical Sciences, Hyderabad",
//   "Bhaskar Medical College, Hyderabad",
//   "Chalmeda Anand Rao Institute of Medical Sciences, Karimnagar",
//   "Kamineni Institute of Medical Sciences, Narketpally",
//   "Mamata Medical College, Khammam",
//   "Mediciti Institute of Medical Sciences, Ghanpur",
//   "Malla Reddy Medical College for Women, Hyderabad",
//   "Malla Reddy Institute of Medical Sciences, Hyderabad",
//   "Mahavir Institute of Medical Sciences, Vikarabad",
//   "Dr. Patnam Mahender Reddy Institute of Medical Sciences, Chevella",
//   "Surabhi Institute of Medical Sciences, Siddipet",


//   "Andhra Medical College, Visakhapatnam",
//   "Guntur Medical College, Guntur",
//   "Siddhartha Medical College, Vijayawada",
//   "Kurnool Medical College, Kurnool",
//   "Sri Venkateswara Medical College, Tirupati",
//   "Rangaraya Medical College, Kakinada",
//   "Government Medical College, Anantapur",
//   "Government Medical College, Kadapa",
//   "Government Medical College, Ongole",
//   "Government Medical College, Machilipatnam",
//   "Government Medical College, Vizianagaram",
//   "Government Medical College, Rajahmundry",
//   "Government Medical College, Eluru",
//   "Government Medical College, Nandyal",
//   "Government Medical College, Paderu",
//   "Government Medical College, Srikakulam",
//   "A. C. Subba Reddy Government Medical College, Nellore",
//   "All India Institute of Medical Sciences (AIIMS), Mangalagiri",
//   "Narayana Medical College, Nellore",
//   "Alluri Sitarama Raju Academy of Medical Sciences, Eluru",
//   "Fathima Institute of Medical Sciences, Kadapa",
//   "Katuri Medical College, Guntur",
//   "GSL Medical College, Rajahmundry",
//   "Konaseema Institute of Medical Sciences, Amalapuram",
//   "NRI Medical College, Mangalagiri",
//   "Apollo Institute of Medical Sciences, Chittoor",
//   "Dr. Pinnamaneni Siddhartha Institute of Medical Sciences, Vijayawada",
//   "Sri Balaji Medical College, Tirupati"
// ];


// export const All_Medical_Colleges_Names = [
//   // Telangana Colleges
//   "Osmania Medical College, Telangana, MBBS, MD/MS, BSc Nursing, Allied Health Sciences",
//   "Gandhi Medical College, Telangana, MBBS, MD/MS, BDS, BSc Nursing, Allied Health Sciences",
//   "Kakatiya Medical College, Telangana, MBBS, MD/MS, BSc Nursing, Allied Health Sciences",
//   "ESIC Medical College, Telangana, MBBS, MD/MS, BPT, Allied Health Sciences",
//   "Government Medical College, Nizamabad, Telangana, MBBS, MD/MS, BSc Nursing",
//   "Government Medical College, Mahabubnagar, Telangana, MBBS, MD/MS, BSc Nursing",
//   "Government Medical College, Siddipet, Telangana, MBBS, MD/MS, BSc Nursing",
//   "Government Medical College, Suryapet, Telangana, MBBS, MD/MS, BSc Nursing",
//   "Government Medical College, Nalgonda, Telangana, MBBS, MD/MS, BSc Nursing",
//   "Rajiv Gandhi Institute of Medical Sciences, Telangana, MBBS, MD/MS, BPT",
//   "Apollo Institute of Medical Sciences, Telangana, MBBS, MD/MS, BPT, Nursing, Allied Health Sciences",
//   "Bhaskar Medical College, Telangana, MBBS, MD/MS, Nursing, Allied Health Sciences",
//   "Chalmeda Anand Rao Institute of Medical Sciences, Telangana, MBBS, MD/MS, BSc Nursing",
//   "Kamineni Institute of Medical Sciences, Telangana, MBBS, MD/MS, BSc Nursing",
//   "Deccan College of Medical Sciences, Telangana, MBBS, BDS, BPT, Pharmacy, BSc Nursing",
//   "Malla Reddy Medical College for Women, Telangana, MBBS, MD/MS, BSc Nursing",
//   "Mahavir Institute of Medical Sciences, Telangana, MBBS, MD/MS, BSc Nursing",
//   "Dr. Patnam Mahender Reddy Institute of Medical Sciences, Telangana, MBBS, MD/MS, BSc Nursing",
//   "Surabhi Institute of Medical Sciences, Telangana, MBBS, MD/MS, BSc Nursing",
//   "CMR Institute of Medical Sciences, Telangana, BSc MLT, Allied Health Sciences",
//   "Nova Institute of Medical Sciences, Telangana, MBBS, MD/MS, BSc Nursing",
//   "Prathima Institute of Medical Sciences, Telangana, MBBS, MD/MS, BSc Nursing",
//   "RVM Institute of Medical Sciences, Telangana, MBBS, MD/MS, BSc Nursing",
//   "Shadan Institute of Medical Sciences, Telangana, MBBS, MD/MS, BSc Nursing",
//   "SVS Medical College, Telangana, MBBS, MD/MS, BSc Nursing",
//   "TRR Institute of Medical Sciences, Telangana, MBBS, MD/MS, BSc Nursing",

//   // Andhra Pradesh Colleges
//   "Andhra Medical College, Andhra Pradesh, MBBS, MD/MS, BSc Nursing, Pharmacy",
//   "Guntur Medical College, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
//   "Kurnool Medical College, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
//   "Siddhartha Medical College, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
//   "Sri Venkateswara Medical College, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
//   "Rangaraya Medical College, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
//   "Government Medical College, Eluru, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
//   "Government Medical College, Vizianagaram, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
//   "Government Medical College, Machilipatnam, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
//   "Government Medical College, Nandyal, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
//   "Government Medical College, Rajahmundry, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
//   "Government Medical College, Anantapur, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
//   "Government Medical College, Kadapa, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
//   "All India Institute of Medical Sciences (AIIMS), Mangalagiri, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
//   "DCMS College of Physiotherapy, Andhra Pradesh, BPT, MPT",
//   "Vijaya Institute of Medical Sciences, Andhra Pradesh, BPT, MPT",
//   "PES Institute of Medical Sciences & Research, Andhra Pradesh, MBBS, MD/MS, BPT, BSc Nursing",
//   "Narayana Medical College, Andhra Pradesh, MBBS, MD/MS, BSc Nursing, Allied Health Sciences",
//   "GSL Medical College, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
//   "Katuri Medical College, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
//   "Konaseema Institute of Medical Sciences, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
//   "NRI Medical College, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
//   "Dr. Pinnamaneni Siddhartha Institute of Medical Sciences, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
//   "Sri Balaji Medical College, Andhra Pradesh, MBBS, MD/MS, BSc Nursing"
// ];
export const Main_Filters = ["Client Enquiry", "Placements", "Timesheet", "Referral Pay", "Payments"];

export const ClientEnquiry_Filters = ["Processing", "Converted", "Waiting List", "Lost"];

export const Placements_Filters = ["On Service", "Replacements", "Termination"];

export const Timesheet_Filters = ["Provider Staff", "Co-provider", "Curate"];

export const ReferralPay_Filters = ["Lead Referral", "Institute Referral", "Staff Referral"];

export const Payments_Filters = ["Invoice Pending", "Collections", "Expenses"];

export const filterColors: Record<string, string> = {

  "Client Enquiry": "bg-blue-200 hover:bg-blue-400 text-gray-800",
  "Placements": "bg-pink-200 hover:bg-pink-400 text-gray-800",
  "Timesheet": "bg-indigo-200 hover:bg-indigo-400 text-gray-800",
  "Referral Pay": "bg-teal-200 hover:bg-teal-400 text-gray-800",
  "Payments": "bg-orange-200 hover:bg-orange-400 text-gray-800",

"Placced":" text-emerald-600",
  "Processing": "bg-yellow-200 hover:bg-yellow-400 text-gray-800",
  "Waiting List": "bg-purple-200 hover:bg-purple-400 text-gray-800",
  "Converted": "bg-green-200 hover:bg-green-400 text-gray-800",
  "Lost": "bg-red-200 hover:bg-red-400 text-gray-800",


  "On Service": "bg-sky-200 hover:bg-sky-400 text-gray-800",
  "Replacements": "bg-pink-200 hover:bg-pink-400 text-gray-800",
  "Termination": "bg-rose-200 hover:bg-rose-400 text-gray-800",

 
  "Provider Staff": "bg-indigo-200 hover:bg-indigo-400 text-gray-800",
  "Co-provider": "bg-cyan-200 hover:bg-cyan-400 text-gray-800",
  "Curate": "bg-violet-200 hover:bg-violet-400 text-gray-800",

  "Lead Referral": "bg-emerald-200 hover:bg-emerald-400 text-gray-800",
  "Institute Referral": "bg-lime-200 hover:bg-lime-400 text-gray-800",
  "Staff Referral": "bg-green-200 hover:bg-green-400 text-gray-800",


  "Invoice Pending": "bg-orange-200 hover:bg-orange-400 text-gray-800",
  "Collections": "bg-amber-200 hover:bg-amber-400 text-gray-800",
  "Expenses": "bg-red-200 hover:bg-red-400 text-gray-800",
};


export const familyRelations = [
  "Father",
  "Mother",
  "Son",
  "Daughter",
  "Brother",
  "Sister",
  "Husband",
  "Wife",
  "Grandfather (Paternal)",
  "Grandmother (Paternal)",
  "Grandfather (Maternal)",
  "Grandmother (Maternal)",
  "Uncle (Paternal)",
  "Aunt (Paternal)",
  "Uncle (Maternal)",
  "Aunt (Maternal)",
  "Cousin (Male)",
  "Cousin (Female)",
  "Nephew",
  "Niece",
  "Father-in-law",
  "Mother-in-law",
  "Brother-in-law",
  "Sister-in-law",
  "Son-in-law",
  "Daughter-in-law",
  "Stepfather",
  "Stepmother",
  "Stepson",
  "Stepdaughter",
  "Godfather",
  "Godmother",
  "Legal Guardian",
  "Other"
];


export const All_Medical_Colleges_Names = [

  "Osmania Medical College, Telangana, MBBS, MD/MS, BPT, BSc Nursing, Medical Lab Technology, Allied Health Sciences, MPH",
  "Gandhi Medical College, Telangana, MBBS, MD/MS, BDS, BPT, BSc Nursing, Allied Health Sciences" ,
  "Kakatiya Medical College, Telangana, MBBS, MD/MS, BPT, BSc Nursing, Allied Health Sciences",
  "ESIC Medical College, Telangana, MBBS, MD/MS, BPT, Allied Health Sciences",
  "Government Medical College, Nizamabad, Telangana, MBBS, MD/MS, BSc Nursing",
  "Government Medical College, Mahabubnagar, Telangana, MBBS, MD/MS, BSc Nursing",
  "Government Medical College, Siddipet, Telangana, MBBS, MD/MS, BSc Nursing",
  "Government Medical College, Suryapet, Telangana, MBBS, MD/MS, BSc Nursing",
  "Government Medical College, Nalgonda, Telangana, MBBS, MD/MS, BSc Nursing",
  "Rajiv Gandhi Institute of Medical Sciences, Telangana, MBBS, MD/MS, BPT",
  "Deccan College of Medical Sciences, Telangana, MBBS, BDS, BPT, Pharmacy, BSc Nursing",
  "Kamineni Institute of Dental Sciences, Telangana, BDS, Allied Health Sciences",
  "Dr. B.R.K.R. Govt Ayurvedic College, Telangana, BAMS, MD Ayurveda",
  "Govt Nizamia Tibbi College, Telangana, BUMS, MD Unani",
  "Durgabai Deshmukh College of Physiotherapy, Telangana, BPT",
  "Kakatiya College of Physiotherapy, Telangana, BPT",
  "Susruta Institute of Physical Medicine & Rehabilitation, Telangana, BPT",
  "Apollo College of Physiotherapy, Telangana, BPT",
  "Government College of Nursing, Warangal, Telangana, BSc Nursing",
  "Govt College of Nursing, Secunderabad, Telangana, BSc Nursing, MSc Nursing",
  "Angel College of Nursing, Telangana, BSc Nursing",
  "Apollo College of Nursing, Telangana, BSc Nursing, MSc Nursing",
  "Institute of Preventive Medicine/Public Health Labs, Telangana, BSc Medical Lab Technology",
  "Shadan College of Medical Lab Technology, Telangana, BSc MLT",
  "SRM Institute of Medical Sciences & Technology, Telangana, BSc MLT",
  "PIMTECH College of BSc MLT, Telangana, BSc MLT",
  "Shaarvani Institute of Medical Sciences, Telangana, BSc MLT",
  "Indian Institute of Public Health, Telangana, MPH",
  "Andhra Medical College, Andhra Pradesh, MBBS, MD/MS, BSc Nursing, Pharmacy",
  "Guntur Medical College, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
  "Kurnool Medical College, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
  "Siddhartha Medical College, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
  "Sri Venkateswara Medical College, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
  "Rangaraya Medical College, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
  "Government Medical College, Eluru, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
  "Government Medical College, Vizianagaram, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
  "Government Medical College, Machilipatnam, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
  "Government Medical College, Nandyal, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
  "Government Medical College, Rajahmundry, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
  "Government Medical College, Anantapur, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
  "Government Medical College, Kadapa, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
  "All India Institute of Medical Sciences (AIIMS) Mangalagiri, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
  "Dr NRS Government Ayurvedic College, Andhra Pradesh, BAMS, MD Ayurveda",
  "S.V. Ayurvedic College, Tirupati, Andhra Pradesh, BAMS",
  "Sri Adi Shiva Sadguru Ayurvedic Medical College, Andhra Pradesh, BAMS",
  "ASR Homoeopathic Medical College, Andhra Pradesh, BHMS",
  "Kugler Memorial Physiotherapy Degree College, Guntur, Andhra Pradesh, BPT",
  "Sri P. Ramireddy Memorial College of Physiotherapy, Kadapa, Andhra Pradesh, BPT",
  "Alluri Sitarama Raju Academy of Medical Sciences, Andhra Pradesh, MBBS, MD/MS",
  "PES Institute of Medical Sciences & Research, Andhra Pradesh, MBBS, MD/MS, BPT, BSc Nursing",
  "DCMS College of Physiotherapy, Andhra Pradesh, BPT, MPT",
  "Vijaya Institute of Medical Sciences, Andhra Pradesh, BPT, MPT",
  "Narayana Medical College, Andhra Pradesh, MBBS, MD/MS, BSc Nursing, Allied Health Sciences",
  "GSL Medical College, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
  "Katuri Medical College, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
  "Konaseema Institute of Medical Sciences, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
  "NRI Medical College, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
  "Dr. Pinnamaneni Siddhartha Institute of Medical Sciences, Andhra Pradesh, MBBS, MD/MS, BSc Nursing",
  "Sri Balaji Medical College, Andhra Pradesh, MBBS, MD/MS, BSc Nursing"
];

