// app/layout.tsx
import type { Metadata, Viewport } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import WrapProvider from "./Provider";
import { NotificationProvider } from "./NotificationProvider";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Curate Health Service",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  userScalable: true,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     <html lang="en" className={poppins.variable}>
      <body className="antialiased">
        <WrapProvider>
          <NotificationProvider>
            {children}
          </NotificationProvider>
        </WrapProvider>
      </body>
    </html>
  );
}
